# Basic dependabot configuration file
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'angular-eslint'
          - 'ng-packagr'
          - 'rxjs'
          - 'tslib'
          - 'zone.js'
