packages:
  - 'packages/*'
  - 'packages/components-angular/projects/*'

catalogs:
  node:
    '@types/node': ^24.0.0
    'ts-node': 10.9.2
  jest:
    '@types/jest': ^30.0.0
    'jest': 30.3.0
    'ts-jest': 29.4.6
