packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': set this to true or false
  '@percy/core': set this to true or false
  core-js-pure: set this to true or false
  cypress: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  iframe-resizer: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  sharp: set this to true or false
  svelte-preprocess: set this to true or false
  unrs-resolver: set this to true or false

catalog:
  '@playwright/test': 1.60.0

catalogs:
  cypress:
    'cypress': 15.14.2
    'cypress-each': 1.14.1
    'cypress-axe': 1.6.0
    'cypress-storybook': 1.0.0
  node:
    '@types/node': 24.0.0
    'ts-node': 10.9.2
  jest:
    '@types/jest': 30.0.0
    'jest': 30.3.0
    'ts-jest': 29.4.9
  stencil/jest:
    '@types/jest': 29.5.14
    'jest': 29.7.0
    'jest-cli': 29.7.0
    'ts-jest': 29.4.9
  'typescript':
    'typescript': 6.0.3
    'typescript-eslint': 8.62.0
  angular:
    '@angular/animations': 22.0.0
    '@angular/build': 22.0.4
    '@angular/cli': 22.0.4
    '@angular/common': 22.0.0
    '@angular/compiler': 22.0.0
    '@angular/compiler-cli': 22.0.0
    '@angular/core': 22.0.0
    '@angular/forms': 22.0.0
    '@angular/platform-browser': 22.0.0
    '@angular/router': 22.0.0
    'angular-eslint': 22.0.0
    'ng-packagr': 22.0.0
    'rxjs': 7.8.2
    'tslib': 2.8.1
    'zone.js': 0.16.1
