name: 'Package Version Updated'
description: 'Indicates when the package.json version has updated in the most recent commit'
branding:
  icon: 'arrow-up'
  color: 'yellow'
inputs:
  path:
    description: 'The path to the package.json'
    required: false
    default: 'package.json'
outputs:
  currentVersion:
    description: 'Current package.json version'
  lastVersion:
    description: 'Package.json version of previous commit'
  versionChanged:
    description: Returns 1 (true) if the version changed and 0 if it is the same
runs:
  using: composite
  steps:
    - name: Compare package.json version
      shell: bash
      run: |
        currentVersion=$(node -pe "require('${{ inputs.path }}').version")
        echo "currentVersion=$currentVersion" >> $GITHUB_OUTPUT
        git checkout HEAD~1 -- ${{ inputs.path }}
        lastVersion=$(node -pe "require('${{ inputs.path }}').version")
        git checkout HEAD -- ${{ inputs.path }}
        echo "lastVersion=$lastVersion" >> $GITHUB_OUTPUT
        [ $currentVersion == $lastVersion ];versionChanged=$?
        echo "versionChanged=$versionChanged" >> $GITHUB_OUTPUT
