name: 'Package Version Updated'
description: 'Indicates when the package.json version has updated in the most recent commit'
branding:
  icon: 'arrow-up'
  color: 'yellow'
inputs:
  path:
    description: 'The path to the package.json'
    required: false
    default: 'package.json'
outputs:
  has-updated:
    description: 'Whether the package.json version has been updated'
  current-package-version:
    description: 'The current package.json version'
runs:
  using: 'node16'
  main: 'index.js'
