title: '[Architecture Decisions] '
labels: ['Architecture Decision Records (ADRs)']
body:
  - type: markdown
    attributes:
      value: |
        ## Context

        What is the issue that we're seeing that is motivating this decision or change?

        ## Decision

        What is the change that we're proposing and/or doing?

        ## Consequences

        What becomes easier or more difficult to do because of this change?

        ## Example (optional)

        If applicable, show a code example to support the decision.
