/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActiveRouteProp, Environment } from "./models/general.model";
export { ActiveRouteProp, Environment } from "./models/general.model";
export namespace Components {
    interface SwisspostInternetFooter {
        /**
          * Label for the "Cookie Settings" button.
         */
        "textCookieSettings": string;
        /**
          * Visually hidden label for the footer.
         */
        "textFooter": string;
    }
    interface SwisspostInternetHeader {
        /**
          * Set the currently activated route. If there is a link matching this URL in the header, it will be highlighted. Will also highlight partly matching URLs. When set to auto, will use current location.href for comparison.
          * @default 'auto'
         */
        "activeRoute": ActiveRouteProp;
        /**
          * Target environment. Choose 'int01' for local testing.
          * @default 'prod'
         */
        "environment": Environment;
        /**
          * Makes the header content span the full width on screens larger than 1440px.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Initial language to be used. Overrides automatic language detection.
         */
        "language"?: 'de' | 'fr' | 'it' | 'en';
        /**
          * Your project id, previously passed as query string parameter serviceId.
         */
        "project": string;
        /**
          * Visually hidden label for the login widget trigger button.
         */
        "textAccessUserLinks": string;
        /**
          * Visually hidden label for the back button.
         */
        "textBack": string;
        /**
          * Visually hidden label for the language menu.
         */
        "textChangeLanguage": string;
        /**
          * Visually hidden label for the close button.
         */
        "textClose": string;
        /**
          * Visually hidden label for the current language. The placeholder `{name}` will be replaced with the name of the currently selected language.
         */
        "textCurrentLanguage": string;
        /**
          * Visually hidden label for the current user. The placeholder `{user}` will be replaced with the full name of the currently logged-in user.
         */
        "textCurrentUser": string;
        /**
          * Visually hidden label for the main navigation element.
         */
        "textMain": string;
        /**
          * Visually hidden label for the burger menu button.
         */
        "textMenu": string;
        /**
          * Visually hidden label for the user menu.
         */
        "textUserLinks": string;
    }
}
export interface SwisspostInternetHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSwisspostInternetHeaderElement;
}
declare global {
    interface HTMLSwisspostInternetFooterElement extends Components.SwisspostInternetFooter, HTMLStencilElement {
    }
    var HTMLSwisspostInternetFooterElement: {
        prototype: HTMLSwisspostInternetFooterElement;
        new (): HTMLSwisspostInternetFooterElement;
    };
    interface HTMLSwisspostInternetHeaderElementEventMap {
        "headerLoaded": void;
    }
    interface HTMLSwisspostInternetHeaderElement extends Components.SwisspostInternetHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSwisspostInternetHeaderElementEventMap>(type: K, listener: (this: HTMLSwisspostInternetHeaderElement, ev: SwisspostInternetHeaderCustomEvent<HTMLSwisspostInternetHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSwisspostInternetHeaderElementEventMap>(type: K, listener: (this: HTMLSwisspostInternetHeaderElement, ev: SwisspostInternetHeaderCustomEvent<HTMLSwisspostInternetHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSwisspostInternetHeaderElement: {
        prototype: HTMLSwisspostInternetHeaderElement;
        new (): HTMLSwisspostInternetHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "swisspost-internet-footer": HTMLSwisspostInternetFooterElement;
        "swisspost-internet-header": HTMLSwisspostInternetHeaderElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface SwisspostInternetFooter {
        /**
          * Label for the "Cookie Settings" button.
         */
        "textCookieSettings": string;
        /**
          * Visually hidden label for the footer.
         */
        "textFooter": string;
    }
    interface SwisspostInternetHeader {
        /**
          * Set the currently activated route. If there is a link matching this URL in the header, it will be highlighted. Will also highlight partly matching URLs. When set to auto, will use current location.href for comparison.
          * @default 'auto'
         */
        "activeRoute"?: ActiveRouteProp;
        /**
          * Target environment. Choose 'int01' for local testing.
          * @default 'prod'
         */
        "environment"?: Environment;
        /**
          * Makes the header content span the full width on screens larger than 1440px.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Initial language to be used. Overrides automatic language detection.
         */
        "language"?: 'de' | 'fr' | 'it' | 'en';
        /**
          * Fires when the header has been rendered to the page.
         */
        "onHeaderLoaded"?: (event: SwisspostInternetHeaderCustomEvent<void>) => void;
        /**
          * Your project id, previously passed as query string parameter serviceId.
         */
        "project": string;
        /**
          * Visually hidden label for the login widget trigger button.
         */
        "textAccessUserLinks": string;
        /**
          * Visually hidden label for the back button.
         */
        "textBack": string;
        /**
          * Visually hidden label for the language menu.
         */
        "textChangeLanguage": string;
        /**
          * Visually hidden label for the close button.
         */
        "textClose": string;
        /**
          * Visually hidden label for the current language. The placeholder `{name}` will be replaced with the name of the currently selected language.
         */
        "textCurrentLanguage": string;
        /**
          * Visually hidden label for the current user. The placeholder `{user}` will be replaced with the full name of the currently logged-in user.
         */
        "textCurrentUser": string;
        /**
          * Visually hidden label for the main navigation element.
         */
        "textMain": string;
        /**
          * Visually hidden label for the burger menu button.
         */
        "textMenu": string;
        /**
          * Visually hidden label for the user menu.
         */
        "textUserLinks": string;
    }

    interface SwisspostInternetFooterAttributes {
        "textFooter": string;
        "textCookieSettings": string;
    }
    interface SwisspostInternetHeaderAttributes {
        "activeRoute": ActiveRouteProp;
        "environment": Environment;
        "fullWidth": boolean;
        "language": 'de' | 'fr' | 'it' | 'en';
        "project": string;
        "textBack": string;
        "textChangeLanguage": string;
        "textClose": string;
        "textCurrentLanguage": string;
        "textCurrentUser": string;
        "textMain": string;
        "textMenu": string;
        "textAccessUserLinks": string;
        "textUserLinks": string;
    }

    interface IntrinsicElements {
        "swisspost-internet-footer": Omit<SwisspostInternetFooter, keyof SwisspostInternetFooterAttributes> & { [K in keyof SwisspostInternetFooter & keyof SwisspostInternetFooterAttributes]?: SwisspostInternetFooter[K] } & { [K in keyof SwisspostInternetFooter & keyof SwisspostInternetFooterAttributes as `attr:${K}`]?: SwisspostInternetFooterAttributes[K] } & { [K in keyof SwisspostInternetFooter & keyof SwisspostInternetFooterAttributes as `prop:${K}`]?: SwisspostInternetFooter[K] } & OneOf<"textFooter", SwisspostInternetFooter["textFooter"], SwisspostInternetFooterAttributes["textFooter"]> & OneOf<"textCookieSettings", SwisspostInternetFooter["textCookieSettings"], SwisspostInternetFooterAttributes["textCookieSettings"]>;
        "swisspost-internet-header": Omit<SwisspostInternetHeader, keyof SwisspostInternetHeaderAttributes> & { [K in keyof SwisspostInternetHeader & keyof SwisspostInternetHeaderAttributes]?: SwisspostInternetHeader[K] } & { [K in keyof SwisspostInternetHeader & keyof SwisspostInternetHeaderAttributes as `attr:${K}`]?: SwisspostInternetHeaderAttributes[K] } & { [K in keyof SwisspostInternetHeader & keyof SwisspostInternetHeaderAttributes as `prop:${K}`]?: SwisspostInternetHeader[K] } & OneOf<"project", SwisspostInternetHeader["project"], SwisspostInternetHeaderAttributes["project"]> & OneOf<"textBack", SwisspostInternetHeader["textBack"], SwisspostInternetHeaderAttributes["textBack"]> & OneOf<"textChangeLanguage", SwisspostInternetHeader["textChangeLanguage"], SwisspostInternetHeaderAttributes["textChangeLanguage"]> & OneOf<"textClose", SwisspostInternetHeader["textClose"], SwisspostInternetHeaderAttributes["textClose"]> & OneOf<"textCurrentLanguage", SwisspostInternetHeader["textCurrentLanguage"], SwisspostInternetHeaderAttributes["textCurrentLanguage"]> & OneOf<"textCurrentUser", SwisspostInternetHeader["textCurrentUser"], SwisspostInternetHeaderAttributes["textCurrentUser"]> & OneOf<"textMain", SwisspostInternetHeader["textMain"], SwisspostInternetHeaderAttributes["textMain"]> & OneOf<"textMenu", SwisspostInternetHeader["textMenu"], SwisspostInternetHeaderAttributes["textMenu"]> & OneOf<"textAccessUserLinks", SwisspostInternetHeader["textAccessUserLinks"], SwisspostInternetHeaderAttributes["textAccessUserLinks"]> & OneOf<"textUserLinks", SwisspostInternetHeader["textUserLinks"], SwisspostInternetHeaderAttributes["textUserLinks"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "swisspost-internet-footer": LocalJSX.IntrinsicElements["swisspost-internet-footer"] & JSXBase.HTMLAttributes<HTMLSwisspostInternetFooterElement>;
            "swisspost-internet-header": LocalJSX.IntrinsicElements["swisspost-internet-header"] & JSXBase.HTMLAttributes<HTMLSwisspostInternetHeaderElement>;
        }
    }
}
