/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HeadingLevel } from "./types/index";
import { BannerType } from "./components/post-banner/banner-types";
import { ButtonType } from "./components/post-closebutton/button-types";
import { SwitchVariant } from "./components/post-language-menu/switch-variants";
import { Placement } from "@floating-ui/dom";
export { HeadingLevel } from "./types/index";
export { BannerType } from "./components/post-banner/banner-types";
export { ButtonType } from "./components/post-closebutton/button-types";
export { SwitchVariant } from "./components/post-language-menu/switch-variants";
export { Placement } from "@floating-ui/dom";
export namespace Components {
    interface PostAccordion {
        /**
          * Collapses all `post-accordion-item`.
         */
        "collapseAll": () => Promise<void>;
        /**
          * Expands all `post-accordion-item`.  If `multiple="true"` is not set and all items are closed, it will open the first one. Otherwise, it will keep the opened one.
         */
        "expandAll": () => Promise<void>;
        /**
          * Defines the hierarchical level of the `post-accordion-item` headers within the headings structure.
         */
        "headingLevel": HeadingLevel;
        /**
          * If `true`, multiple `post-accordion-item` can be open at the same time.
          * @default false
         */
        "multiple": boolean;
        /**
          * Toggles the `post-accordion-item` with the given id.
         */
        "toggle": (id: string) => Promise<void>;
    }
    interface PostAccordionItem {
        /**
          * If `true`, the element is collapsed otherwise it is displayed.
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Defines the hierarchical level of the accordion item header within the headings structure.
          * @deprecated set the `heading-level` property on the parent `post-accordion` instead.
         */
        "headingLevel"?: HeadingLevel;
        /**
          * Triggers the collapse programmatically.
         */
        "toggle": (force?: boolean) => Promise<boolean>;
    }
    interface PostAvatar {
        /**
          * Provides a custom description for the avatar, used for accessibility purposes.
         */
        "description"?: string;
        /**
          * Defines the users email address associated with a gravatar profile picture.
         */
        "email"?: string;
        /**
          * Defines the users firstname.
         */
        "firstname": string;
        /**
          * Defines the users lastname.
         */
        "lastname"?: string;
        /**
          * Defines the company internal userId.<post-banner type="warning" data-size="sm"><p>Can only be used on post.ch domains!</p></post-banner>
         */
        "userid"?: string;
    }
    interface PostBackToTop {
        /**
          * The label of the back-to-top button, intended solely for accessibility purposes. This label is always hidden from view.
         */
        "textBackToTop": string;
    }
    interface PostBanner {
        /**
          * Triggers banner dismissal programmatically (same as clicking on the close button (×)).
         */
        "dismiss": () => Promise<void>;
        /**
          * The type of the banner.
          * @default 'info'
         */
        "type": BannerType;
    }
    interface PostBreadcrumbItem {
        /**
          * The optional URL to which the breadcrumb item will link.
         */
        "url"?: string | URL;
    }
    interface PostBreadcrumbs {
        /**
          * The URL for the home breadcrumb item.
         */
        "homeUrl": string;
        /**
          * The accessible label for the breadcrumb component.
         */
        "textBreadcrumbs": string;
        /**
          * The text label for the home breadcrumb item.
         */
        "textHome": string;
        /**
          * The accessible label for the breadcrumb menu when breadcrumb items are concatenated.
         */
        "textMoreItems": string;
    }
    /**
     * @class PostCardControl - representing a stencil component
     */
    interface PostCardControl {
        /**
          * Defines the `checked` attribute of the control. If `true`, the control is selected at its value will be included in the forms' data.
          * @default false
         */
        "checked": boolean;
        /**
          * Defines the description in the control-label.
         */
        "description"?: string;
        /**
          * Defines the `disabled` attribute of the control. If `true`, the user can not interact with the control and the controls value will not be included in the forms' data.
          * @default false
         */
        "disabled": boolean;
        /**
          * A hidden public method to reset the group controls `checked` state to `false`.
         */
        "groupReset": () => Promise<void>;
        /**
          * Defines the icon `name` inside the card. <post-banner data-size="sm"><p>If not set the icon will not show up.</p></post-banner>
         */
        "icon"?: string;
        /**
          * Defines the text in the control-label.
         */
        "label": string;
        /**
          * Defines the `name` attribute of the control. <post-banner data-size="sm"><p>This is a required property, when the control should participate in a native `form`. If not specified, a native `form` will never contain this controls value.</p></post-banner> <post-banner data-size="sm"><p>This is a required property, when the control is used with type `radio`.</p></post-banner>
         */
        "name"?: string;
        /**
          * A public method to reset the controls `checked` and `validity` state. The validity state is set to `undefined`, so it's neither valid nor invalid.
         */
        "reset": () => Promise<void>;
        /**
          * Defines the `type` attribute of the control.
         */
        "type": 'checkbox' | 'radio';
        /**
          * Defines the validation `validity` of the control. To reset validity to an undefined state, simply remove the attribute from the control.
         */
        "validity"?: boolean;
        /**
          * Defines the `value` attribute of the control. <post-banner data-size="sm"><p>This is a required property, when the control is used with type `radio`.</p></post-banner>
         */
        "value"?: string;
    }
    interface PostClosebutton {
        /**
          * Overrides the close button's type ("button" by default)
          * @default 'button'
         */
        "buttonType"?: ButtonType;
    }
    interface PostCollapsible {
        /**
          * If `true`, the element is collapsed otherwise it is displayed.
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Triggers the collapse programmatically. If there is a collapsing transition running already, it will be reversed. If no parameter is provided, the current state (this.isExpanded) will be toggled.
         */
        "toggle": (shouldExpand?: boolean) => Promise<boolean>;
    }
    interface PostCollapsibleTrigger {
        /**
          * Link the trigger to a post-collapsible with this id
         */
        "for": string;
        /**
          * Update the "aria-controls" and "aria-expanded" attributes on the trigger button
         */
        "update": () => Promise<void>;
    }
    interface PostEnvTest {
    }
    interface PostFooter {
        /**
          * The textFooter to add to the footer (visually hidden).
         */
        "textFooter": string;
    }
    interface PostHeader {
        /**
          * The label of the burger menu button.
         */
        "textMenu": string;
        /**
          * Toggles the burger navigation menu.
         */
        "toggleBurgerMenu": (force?: boolean) => Promise<void>;
    }
    /**
     * @class PostIcon - representing a stencil component
     */
    interface PostIcon {
        /**
          * The name of the animation.
         */
        "animation"?: Animation;
        /**
          * The base path, where the icons are located (must be a public url).<br/>Leave this field empty to use the default cdn url.
         */
        "base"?: string;
        /**
          * When set to `true`, the icon will be flipped horizontally.
          * @default false
         */
        "flipH"?: boolean;
        /**
          * When set to `true`, the icon will be flipped vertically.
          * @default false
         */
        "flipV"?: boolean;
        /**
          * The name/id of the icon (e.g. 1000, 1001, ...).
         */
        "name": string;
        /**
          * The number of degree for the css rotate transformation.
         */
        "rotate"?: number;
        /**
          * The number for the css scale transformation.
         */
        "scale"?: number;
    }
    interface PostLanguageMenu {
        /**
          * A title for the list of language options
         */
        "textChangeLanguage": string;
        /**
          * An accessible description text for the list of language options. The `#name` placeholder is dynamic and will be replaced with the active language name.
         */
        "textCurrentLanguage": string;
        /**
          * Whether the component is rendered as a list or a menu
          * @default 'list'
         */
        "variant": SwitchVariant;
    }
    interface PostLanguageMenuItem {
        /**
          * If set to `true`, the language option is considered the current language for the page.
         */
        "active"?: boolean;
        /**
          * The ISO 639 language code, formatted according to [RFC 5646 (also known as BCP 47)](https://datatracker.ietf.org/doc/html/rfc5646). For example, "de".
         */
        "code": string;
        /**
          * The full name of the language. For example, "Deutsch".
         */
        "name"?: string;
        /**
          * Selects the language option programmatically.
         */
        "select": () => Promise<void>;
        /**
          * The URL used for the href attribute of the internal anchor. This field is optional; if not provided, a button will be used internally instead of an anchor.
         */
        "url"?: string;
        /**
          * To communicate the variant prop from the parent (post-language-menu) component to the child (post-language-menu-item) component. See parent docs for a description about the property itself.
         */
        "variant"?: SwitchVariant;
    }
    interface PostLinkarea {
    }
    interface PostLogo {
        /**
          * The URL to which the user is redirected upon clicking the logo.
         */
        "url"?: string | URL;
    }
    interface PostMainnavigation {
        /**
          * Defines the accessible label for the navigation element. This text is used as the `aria-label` attribute to provide screen reader users with a description of the navigation's purpose.
         */
        "textMain": string;
    }
    interface PostMegadropdown {
        /**
          * Sets focus to the first focusable element within the component.
         */
        "focusFirst": () => Promise<void>;
        /**
          * Hides the dropdown with an animation.
         */
        "hide": (focusParent?: boolean, forceClose?: boolean) => Promise<void>;
        /**
          * Displays the dropdown.
         */
        "show": () => Promise<void>;
        /**
          * A label for the back button visible on tablet and mobile
         */
        "textBack": string;
        /**
          * An accessible label for the close button visible on desktop
         */
        "textClose": string;
        /**
          * Toggles the dropdown visibility based on its current state.
         */
        "toggle": () => Promise<void>;
    }
    interface PostMegadropdownTrigger {
        /**
          * Sets the trigger state to be active or inactive.
          * @default false
         */
        "active": boolean;
        /**
          * ID of the mega dropdown element that this trigger is linked to. Used to open and close the specified mega dropdown.
         */
        "for": string;
    }
    interface PostMenu {
        /**
          * Hides the popover menu and restores focus to the previously focused element.
         */
        "hide": () => Promise<void>;
        /**
          * A descriptive label that clearly identifies the menu’s content so assistive technologies can convey its purpose.
         */
        "label": string;
        /**
          * Defines the position of the menu relative to its trigger. Menus are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries. For supported values and behavior details, see the [Floating UI placement documentation](https://floating-ui.com/docs/computePosition#placement).
          * @default 'bottom'
         */
        "placement"?: Placement;
        /**
          * Displays the popover menu, focusing the first menu item.
          * @param target - The HTML element relative to which the popover menu should be displayed.
         */
        "show": (target: HTMLElement) => Promise<void>;
        /**
          * Toggles the menu visibility based on its current state.
         */
        "toggle": (target: HTMLElement) => Promise<void>;
    }
    interface PostMenuItem {
    }
    interface PostMenuTrigger {
        /**
          * ID of the menu element that this trigger is linked to. Used to open and close the specified menu.
         */
        "for": string;
    }
    interface PostPagination {
        /**
          * The total number of items in the collection.
         */
        "collectionSize": number;
        /**
          * If true, the pagination is disabled.
         */
        "disabled"?: boolean;
        /**
          * A descriptive label for the pagination navigation, used by assistive technologies.
         */
        "label": string;
        /**
          * The current active page number.  **If not specified, defaults to the first page.**
         */
        "page"?: number;
        /**
          * The number of items per page.
         */
        "pageSize": number;
        /**
          * Prefix text for the first page label.
         */
        "textFirst": string;
        /**
          * Prefix text for the last page label.
         */
        "textLast": string;
        /**
          * Accessible label for the next page button.
         */
        "textNext": string;
        /**
          * Prefix text for page number labels.
         */
        "textPage": string;
        /**
          * Accessible label for the previous page button.
         */
        "textPrevious": string;
    }
    interface PostPopover {
        /**
          * Show a little indicator arrow
          * @default true
         */
        "arrow"?: boolean;
        /**
          * Programmatically hide this popover
         */
        "hide": () => Promise<void>;
        /**
          * Defines the position of the popover relative to its trigger. Popovers are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries. For supported values and behavior details, see the [Floating UI placement documentation](https://floating-ui.com/docs/computePosition#placement).
          * @default 'top'
         */
        "placement"?: Placement;
        /**
          * Programmatically display the popover
          * @param target A focusable element inside the <post-popover-trigger> component that controls the popover
         */
        "show": (target: HTMLElement) => Promise<void>;
        /**
          * Define the text of the close button for assistive technology
         */
        "textClose": string;
        /**
          * Toggle popover display
          * @param target A focusable element inside the <post-popover-trigger> component that controls the popover
          * @param force Pass true to always show or false to always hide
         */
        "toggle": (target: HTMLElement, force?: boolean) => Promise<void>;
    }
    interface PostPopoverTrigger {
        /**
          * ID of the popover element that this trigger is linked to. Used to open and close the popover.
         */
        "for"?: string;
    }
    interface PostPopovercontainer {
        /**
          * Animation style
          * @default null
         */
        "animation"?: 'pop-in' | null;
        /**
          * Whether or not to display a little pointer arrow
          * @default false
         */
        "arrow"?: boolean;
        /**
          * Gap between the edge of the page and the popovercontainer
          * @default 8
         */
        "edgeGap"?: number;
        /**
          * Programmatically hide the popovercontainer
         */
        "hide": () => Promise<void>;
        /**
          * Defines the placement of the popovercontainer according to the floating-ui options available at https://floating-ui.com/docs/computePosition#placement. Popovercontainers are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries.
          * @default 'top'
         */
        "placement"?: Placement;
        /**
          * Enables a safespace through which the cursor can be moved without the popover being disabled
         */
        "safeSpace"?: 'triangle' | 'trapezoid';
        /**
          * Programmatically display the popovercontainer
          * @param target A focusable element inside the <post-popover-trigger> component that controls the popover
         */
        "show": (target: HTMLElement) => Promise<void>;
        /**
          * Toggle popovercontainer display
          * @param target A focusable element inside the <post-popover-trigger> component that controls the popover
          * @param force Pass true to always show or false to always hide
         */
        "toggle": (target: HTMLElement, force?: boolean) => Promise<boolean>;
    }
    interface PostRating {
        /**
          * Defines the rating that the component should show.
          * @default 0
         */
        "currentRating": number;
        /**
          * A hidden, descriptive label that explains the role of the rating component to assistive technologies.
         */
        "label": string;
        /**
          * Defines if the component is readonly or not. This usually should be used together with the `currentRating` property.
          * @default false
         */
        "readonly": boolean;
        /**
          * Defines the total amount of stars rendered in the component.
          * @default 5
         */
        "stars": number;
    }
    interface PostStepper {
        /**
          * Defines the currently active step
          * @default -1
         */
        "currentIndex": number;
        /**
          * "Completed step" label for accessibility
         */
        "textCompletedStep": string;
        /**
          * "Current step" label for accessibility
         */
        "textCurrentStep": string;
        /**
          * Label for the "Step N:" indicator for mobile view. Use `#number` as a placeholder — it will be replaced with the current step number at runtime.
         */
        "textStepNumber": string;
    }
    interface PostStepperItem {
    }
    interface PostTabItem {
        /**
          * The name of the tab, used to associate it with a tab panel or identify the active tab in panel mode.
         */
        "name": string;
    }
    interface PostTabPanel {
        /**
          * The name of the tab that this panel is associated with.
         */
        "for": string;
    }
    interface PostTabs {
        /**
          * The name of the tab in the panel mode that is initially active. Changing this value after initialization has no effect. If not specified, defaults to the first tab.
         */
        "activeTab"?: string;
        /**
          * When set to true, this property allows the tabs container to span the Changing this value after initialization has no effect. full width of the screen, from edge to edge.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * The accessible label for the tabs component in navigation mode.
         */
        "label"?: string;
        /**
          * Shows the panel with the given name and selects its associated tab. Any other panel that was previously shown becomes hidden and its associated tab is unselected.
         */
        "show": (tabName: string) => Promise<void>;
    }
    interface PostTogglebutton {
        /**
          * If `true`, the button is in the "on" state, otherwise it is in the "off" state.
          * @default false
         */
        "toggled": boolean;
    }
    interface PostTooltip {
        /**
          * Choose a tooltip animation
         */
        "animation"?: 'pop-in';
        /**
          * Whether or not to display a little pointer arrow
          * @default false
         */
        "arrow"?: boolean;
        /**
          * Programmatically hide this tooltip.
         */
        "hide": () => Promise<void>;
        /**
          * Indicates the open state of the tooltip
          * @default false
         */
        "open": boolean;
        /**
          * Defines the position of the tooltip relative to its trigger. Tooltips are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries. For supported values and behavior details, see the [Floating UI placement documentation](https://floating-ui.com/docs/computePosition#placement).
          * @default 'top'
         */
        "placement"?: Placement;
        /**
          * Programmatically display the tooltip.
          * @param target An element where the tooltip should be shown
         */
        "show": (target: HTMLElement) => Promise<void>;
        /**
          * Toggle tooltip display.
          * @param target An element where the tooltip should be shown
          * @param force Pass true to always show or false to always hide
         */
        "toggle": (target: HTMLElement, force?: boolean) => Promise<void>;
    }
    interface PostTooltipTrigger {
        /**
          * Delay (in milliseconds) before the tooltip is shown.
          * @default 0
         */
        "delay": number;
        /**
          * ID of the tooltip element that this trigger is linked to.
         */
        "for": string;
    }
}
export interface PostBannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostBannerElement;
}
export interface PostCardControlCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostCardControlElement;
}
export interface PostCollapsibleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostCollapsibleElement;
}
export interface PostLanguageMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostLanguageMenuItemElement;
}
export interface PostMegadropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostMegadropdownElement;
}
export interface PostMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostMenuElement;
}
export interface PostPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostPaginationElement;
}
export interface PostPopovercontainerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostPopovercontainerElement;
}
export interface PostRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostRatingElement;
}
export interface PostTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPostTabsElement;
}
declare global {
    interface HTMLPostAccordionElement extends Components.PostAccordion, HTMLStencilElement {
    }
    var HTMLPostAccordionElement: {
        prototype: HTMLPostAccordionElement;
        new (): HTMLPostAccordionElement;
    };
    interface HTMLPostAccordionItemElement extends Components.PostAccordionItem, HTMLStencilElement {
    }
    var HTMLPostAccordionItemElement: {
        prototype: HTMLPostAccordionItemElement;
        new (): HTMLPostAccordionItemElement;
    };
    interface HTMLPostAvatarElement extends Components.PostAvatar, HTMLStencilElement {
    }
    var HTMLPostAvatarElement: {
        prototype: HTMLPostAvatarElement;
        new (): HTMLPostAvatarElement;
    };
    interface HTMLPostBackToTopElement extends Components.PostBackToTop, HTMLStencilElement {
    }
    var HTMLPostBackToTopElement: {
        prototype: HTMLPostBackToTopElement;
        new (): HTMLPostBackToTopElement;
    };
    interface HTMLPostBannerElementEventMap {
        "postDismissed": void;
    }
    interface HTMLPostBannerElement extends Components.PostBanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostBannerElementEventMap>(type: K, listener: (this: HTMLPostBannerElement, ev: PostBannerCustomEvent<HTMLPostBannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostBannerElementEventMap>(type: K, listener: (this: HTMLPostBannerElement, ev: PostBannerCustomEvent<HTMLPostBannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostBannerElement: {
        prototype: HTMLPostBannerElement;
        new (): HTMLPostBannerElement;
    };
    interface HTMLPostBreadcrumbItemElement extends Components.PostBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLPostBreadcrumbItemElement: {
        prototype: HTMLPostBreadcrumbItemElement;
        new (): HTMLPostBreadcrumbItemElement;
    };
    interface HTMLPostBreadcrumbsElement extends Components.PostBreadcrumbs, HTMLStencilElement {
    }
    var HTMLPostBreadcrumbsElement: {
        prototype: HTMLPostBreadcrumbsElement;
        new (): HTMLPostBreadcrumbsElement;
    };
    interface HTMLPostCardControlElementEventMap {
        "postInput": { state: boolean; value: string };
        "postChange": { state: boolean; value: string };
    }
    /**
     * @class PostCardControl - representing a stencil component
     */
    interface HTMLPostCardControlElement extends Components.PostCardControl, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostCardControlElementEventMap>(type: K, listener: (this: HTMLPostCardControlElement, ev: PostCardControlCustomEvent<HTMLPostCardControlElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostCardControlElementEventMap>(type: K, listener: (this: HTMLPostCardControlElement, ev: PostCardControlCustomEvent<HTMLPostCardControlElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostCardControlElement: {
        prototype: HTMLPostCardControlElement;
        new (): HTMLPostCardControlElement;
    };
    interface HTMLPostClosebuttonElement extends Components.PostClosebutton, HTMLStencilElement {
    }
    var HTMLPostClosebuttonElement: {
        prototype: HTMLPostClosebuttonElement;
        new (): HTMLPostClosebuttonElement;
    };
    interface HTMLPostCollapsibleElementEventMap {
        "postToggle": boolean;
    }
    interface HTMLPostCollapsibleElement extends Components.PostCollapsible, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostCollapsibleElementEventMap>(type: K, listener: (this: HTMLPostCollapsibleElement, ev: PostCollapsibleCustomEvent<HTMLPostCollapsibleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostCollapsibleElementEventMap>(type: K, listener: (this: HTMLPostCollapsibleElement, ev: PostCollapsibleCustomEvent<HTMLPostCollapsibleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostCollapsibleElement: {
        prototype: HTMLPostCollapsibleElement;
        new (): HTMLPostCollapsibleElement;
    };
    interface HTMLPostCollapsibleTriggerElement extends Components.PostCollapsibleTrigger, HTMLStencilElement {
    }
    var HTMLPostCollapsibleTriggerElement: {
        prototype: HTMLPostCollapsibleTriggerElement;
        new (): HTMLPostCollapsibleTriggerElement;
    };
    interface HTMLPostEnvTestElement extends Components.PostEnvTest, HTMLStencilElement {
    }
    var HTMLPostEnvTestElement: {
        prototype: HTMLPostEnvTestElement;
        new (): HTMLPostEnvTestElement;
    };
    interface HTMLPostFooterElement extends Components.PostFooter, HTMLStencilElement {
    }
    var HTMLPostFooterElement: {
        prototype: HTMLPostFooterElement;
        new (): HTMLPostFooterElement;
    };
    interface HTMLPostHeaderElement extends Components.PostHeader, HTMLStencilElement {
    }
    var HTMLPostHeaderElement: {
        prototype: HTMLPostHeaderElement;
        new (): HTMLPostHeaderElement;
    };
    /**
     * @class PostIcon - representing a stencil component
     */
    interface HTMLPostIconElement extends Components.PostIcon, HTMLStencilElement {
    }
    var HTMLPostIconElement: {
        prototype: HTMLPostIconElement;
        new (): HTMLPostIconElement;
    };
    interface HTMLPostLanguageMenuElement extends Components.PostLanguageMenu, HTMLStencilElement {
    }
    var HTMLPostLanguageMenuElement: {
        prototype: HTMLPostLanguageMenuElement;
        new (): HTMLPostLanguageMenuElement;
    };
    interface HTMLPostLanguageMenuItemElementEventMap {
        "postChange": string;
        "postLanguageMenuItemInitiallyActive": string;
    }
    interface HTMLPostLanguageMenuItemElement extends Components.PostLanguageMenuItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostLanguageMenuItemElementEventMap>(type: K, listener: (this: HTMLPostLanguageMenuItemElement, ev: PostLanguageMenuItemCustomEvent<HTMLPostLanguageMenuItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostLanguageMenuItemElementEventMap>(type: K, listener: (this: HTMLPostLanguageMenuItemElement, ev: PostLanguageMenuItemCustomEvent<HTMLPostLanguageMenuItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostLanguageMenuItemElement: {
        prototype: HTMLPostLanguageMenuItemElement;
        new (): HTMLPostLanguageMenuItemElement;
    };
    interface HTMLPostLinkareaElement extends Components.PostLinkarea, HTMLStencilElement {
    }
    var HTMLPostLinkareaElement: {
        prototype: HTMLPostLinkareaElement;
        new (): HTMLPostLinkareaElement;
    };
    interface HTMLPostLogoElement extends Components.PostLogo, HTMLStencilElement {
    }
    var HTMLPostLogoElement: {
        prototype: HTMLPostLogoElement;
        new (): HTMLPostLogoElement;
    };
    interface HTMLPostMainnavigationElement extends Components.PostMainnavigation, HTMLStencilElement {
    }
    var HTMLPostMainnavigationElement: {
        prototype: HTMLPostMainnavigationElement;
        new (): HTMLPostMainnavigationElement;
    };
    interface HTMLPostMegadropdownElementEventMap {
        "postToggleMegadropdown": { isVisible: boolean; focusParent?: boolean };
    }
    interface HTMLPostMegadropdownElement extends Components.PostMegadropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostMegadropdownElementEventMap>(type: K, listener: (this: HTMLPostMegadropdownElement, ev: PostMegadropdownCustomEvent<HTMLPostMegadropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostMegadropdownElementEventMap>(type: K, listener: (this: HTMLPostMegadropdownElement, ev: PostMegadropdownCustomEvent<HTMLPostMegadropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostMegadropdownElement: {
        prototype: HTMLPostMegadropdownElement;
        new (): HTMLPostMegadropdownElement;
    };
    interface HTMLPostMegadropdownTriggerElement extends Components.PostMegadropdownTrigger, HTMLStencilElement {
    }
    var HTMLPostMegadropdownTriggerElement: {
        prototype: HTMLPostMegadropdownTriggerElement;
        new (): HTMLPostMegadropdownTriggerElement;
    };
    interface HTMLPostMenuElementEventMap {
        "toggleMenu": boolean;
    }
    interface HTMLPostMenuElement extends Components.PostMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostMenuElementEventMap>(type: K, listener: (this: HTMLPostMenuElement, ev: PostMenuCustomEvent<HTMLPostMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostMenuElementEventMap>(type: K, listener: (this: HTMLPostMenuElement, ev: PostMenuCustomEvent<HTMLPostMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostMenuElement: {
        prototype: HTMLPostMenuElement;
        new (): HTMLPostMenuElement;
    };
    interface HTMLPostMenuItemElement extends Components.PostMenuItem, HTMLStencilElement {
    }
    var HTMLPostMenuItemElement: {
        prototype: HTMLPostMenuItemElement;
        new (): HTMLPostMenuItemElement;
    };
    interface HTMLPostMenuTriggerElement extends Components.PostMenuTrigger, HTMLStencilElement {
    }
    var HTMLPostMenuTriggerElement: {
        prototype: HTMLPostMenuTriggerElement;
        new (): HTMLPostMenuTriggerElement;
    };
    interface HTMLPostPaginationElementEventMap {
        "postChange": number;
    }
    interface HTMLPostPaginationElement extends Components.PostPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostPaginationElementEventMap>(type: K, listener: (this: HTMLPostPaginationElement, ev: PostPaginationCustomEvent<HTMLPostPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostPaginationElementEventMap>(type: K, listener: (this: HTMLPostPaginationElement, ev: PostPaginationCustomEvent<HTMLPostPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostPaginationElement: {
        prototype: HTMLPostPaginationElement;
        new (): HTMLPostPaginationElement;
    };
    interface HTMLPostPopoverElement extends Components.PostPopover, HTMLStencilElement {
    }
    var HTMLPostPopoverElement: {
        prototype: HTMLPostPopoverElement;
        new (): HTMLPostPopoverElement;
    };
    interface HTMLPostPopoverTriggerElement extends Components.PostPopoverTrigger, HTMLStencilElement {
    }
    var HTMLPostPopoverTriggerElement: {
        prototype: HTMLPostPopoverTriggerElement;
        new (): HTMLPostPopoverTriggerElement;
    };
    interface HTMLPostPopovercontainerElementEventMap {
        "postBeforeShow": { first?: boolean };
        "postShow": { first?: boolean };
        "postHide": any;
        "postBeforeToggle": { willOpen: boolean };
        "postToggle": { isOpen: boolean };
    }
    interface HTMLPostPopovercontainerElement extends Components.PostPopovercontainer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostPopovercontainerElementEventMap>(type: K, listener: (this: HTMLPostPopovercontainerElement, ev: PostPopovercontainerCustomEvent<HTMLPostPopovercontainerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostPopovercontainerElementEventMap>(type: K, listener: (this: HTMLPostPopovercontainerElement, ev: PostPopovercontainerCustomEvent<HTMLPostPopovercontainerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostPopovercontainerElement: {
        prototype: HTMLPostPopovercontainerElement;
        new (): HTMLPostPopovercontainerElement;
    };
    interface HTMLPostRatingElementEventMap {
        "postInput": { value: number };
        "postChange": { value: number };
    }
    interface HTMLPostRatingElement extends Components.PostRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostRatingElementEventMap>(type: K, listener: (this: HTMLPostRatingElement, ev: PostRatingCustomEvent<HTMLPostRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostRatingElementEventMap>(type: K, listener: (this: HTMLPostRatingElement, ev: PostRatingCustomEvent<HTMLPostRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostRatingElement: {
        prototype: HTMLPostRatingElement;
        new (): HTMLPostRatingElement;
    };
    interface HTMLPostStepperElement extends Components.PostStepper, HTMLStencilElement {
    }
    var HTMLPostStepperElement: {
        prototype: HTMLPostStepperElement;
        new (): HTMLPostStepperElement;
    };
    interface HTMLPostStepperItemElement extends Components.PostStepperItem, HTMLStencilElement {
    }
    var HTMLPostStepperItemElement: {
        prototype: HTMLPostStepperItemElement;
        new (): HTMLPostStepperItemElement;
    };
    interface HTMLPostTabItemElement extends Components.PostTabItem, HTMLStencilElement {
    }
    var HTMLPostTabItemElement: {
        prototype: HTMLPostTabItemElement;
        new (): HTMLPostTabItemElement;
    };
    interface HTMLPostTabPanelElement extends Components.PostTabPanel, HTMLStencilElement {
    }
    var HTMLPostTabPanelElement: {
        prototype: HTMLPostTabPanelElement;
        new (): HTMLPostTabPanelElement;
    };
    interface HTMLPostTabsElementEventMap {
        "postChange": string;
    }
    interface HTMLPostTabsElement extends Components.PostTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPostTabsElementEventMap>(type: K, listener: (this: HTMLPostTabsElement, ev: PostTabsCustomEvent<HTMLPostTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPostTabsElementEventMap>(type: K, listener: (this: HTMLPostTabsElement, ev: PostTabsCustomEvent<HTMLPostTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPostTabsElement: {
        prototype: HTMLPostTabsElement;
        new (): HTMLPostTabsElement;
    };
    interface HTMLPostTogglebuttonElement extends Components.PostTogglebutton, HTMLStencilElement {
    }
    var HTMLPostTogglebuttonElement: {
        prototype: HTMLPostTogglebuttonElement;
        new (): HTMLPostTogglebuttonElement;
    };
    interface HTMLPostTooltipElement extends Components.PostTooltip, HTMLStencilElement {
    }
    var HTMLPostTooltipElement: {
        prototype: HTMLPostTooltipElement;
        new (): HTMLPostTooltipElement;
    };
    interface HTMLPostTooltipTriggerElement extends Components.PostTooltipTrigger, HTMLStencilElement {
    }
    var HTMLPostTooltipTriggerElement: {
        prototype: HTMLPostTooltipTriggerElement;
        new (): HTMLPostTooltipTriggerElement;
    };
    interface HTMLElementTagNameMap {
        "post-accordion": HTMLPostAccordionElement;
        "post-accordion-item": HTMLPostAccordionItemElement;
        "post-avatar": HTMLPostAvatarElement;
        "post-back-to-top": HTMLPostBackToTopElement;
        "post-banner": HTMLPostBannerElement;
        "post-breadcrumb-item": HTMLPostBreadcrumbItemElement;
        "post-breadcrumbs": HTMLPostBreadcrumbsElement;
        "post-card-control": HTMLPostCardControlElement;
        "post-closebutton": HTMLPostClosebuttonElement;
        "post-collapsible": HTMLPostCollapsibleElement;
        "post-collapsible-trigger": HTMLPostCollapsibleTriggerElement;
        "post-env-test": HTMLPostEnvTestElement;
        "post-footer": HTMLPostFooterElement;
        "post-header": HTMLPostHeaderElement;
        "post-icon": HTMLPostIconElement;
        "post-language-menu": HTMLPostLanguageMenuElement;
        "post-language-menu-item": HTMLPostLanguageMenuItemElement;
        "post-linkarea": HTMLPostLinkareaElement;
        "post-logo": HTMLPostLogoElement;
        "post-mainnavigation": HTMLPostMainnavigationElement;
        "post-megadropdown": HTMLPostMegadropdownElement;
        "post-megadropdown-trigger": HTMLPostMegadropdownTriggerElement;
        "post-menu": HTMLPostMenuElement;
        "post-menu-item": HTMLPostMenuItemElement;
        "post-menu-trigger": HTMLPostMenuTriggerElement;
        "post-pagination": HTMLPostPaginationElement;
        "post-popover": HTMLPostPopoverElement;
        "post-popover-trigger": HTMLPostPopoverTriggerElement;
        "post-popovercontainer": HTMLPostPopovercontainerElement;
        "post-rating": HTMLPostRatingElement;
        "post-stepper": HTMLPostStepperElement;
        "post-stepper-item": HTMLPostStepperItemElement;
        "post-tab-item": HTMLPostTabItemElement;
        "post-tab-panel": HTMLPostTabPanelElement;
        "post-tabs": HTMLPostTabsElement;
        "post-togglebutton": HTMLPostTogglebuttonElement;
        "post-tooltip": HTMLPostTooltipElement;
        "post-tooltip-trigger": HTMLPostTooltipTriggerElement;
    }
}
declare namespace LocalJSX {
    interface PostAccordion {
        /**
          * Defines the hierarchical level of the `post-accordion-item` headers within the headings structure.
         */
        "headingLevel": HeadingLevel;
        /**
          * If `true`, multiple `post-accordion-item` can be open at the same time.
          * @default false
         */
        "multiple"?: boolean;
    }
    interface PostAccordionItem {
        /**
          * If `true`, the element is collapsed otherwise it is displayed.
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Defines the hierarchical level of the accordion item header within the headings structure.
          * @deprecated set the `heading-level` property on the parent `post-accordion` instead.
         */
        "headingLevel"?: HeadingLevel;
    }
    interface PostAvatar {
        /**
          * Provides a custom description for the avatar, used for accessibility purposes.
         */
        "description"?: string;
        /**
          * Defines the users email address associated with a gravatar profile picture.
         */
        "email"?: string;
        /**
          * Defines the users firstname.
         */
        "firstname": string;
        /**
          * Defines the users lastname.
         */
        "lastname"?: string;
        /**
          * Defines the company internal userId.<post-banner type="warning" data-size="sm"><p>Can only be used on post.ch domains!</p></post-banner>
         */
        "userid"?: string;
    }
    interface PostBackToTop {
        /**
          * The label of the back-to-top button, intended solely for accessibility purposes. This label is always hidden from view.
         */
        "textBackToTop": string;
    }
    interface PostBanner {
        /**
          * An event emitted when the banner element is dismissed, after the transition. It has no payload and only relevant for dismissible banners.
         */
        "onPostDismissed"?: (event: PostBannerCustomEvent<void>) => void;
        /**
          * The type of the banner.
          * @default 'info'
         */
        "type"?: BannerType;
    }
    interface PostBreadcrumbItem {
        /**
          * The optional URL to which the breadcrumb item will link.
         */
        "url"?: string | URL;
    }
    interface PostBreadcrumbs {
        /**
          * The URL for the home breadcrumb item.
         */
        "homeUrl": string;
        /**
          * The accessible label for the breadcrumb component.
         */
        "textBreadcrumbs": string;
        /**
          * The text label for the home breadcrumb item.
         */
        "textHome": string;
        /**
          * The accessible label for the breadcrumb menu when breadcrumb items are concatenated.
         */
        "textMoreItems": string;
    }
    /**
     * @class PostCardControl - representing a stencil component
     */
    interface PostCardControl {
        /**
          * Defines the `checked` attribute of the control. If `true`, the control is selected at its value will be included in the forms' data.
          * @default false
         */
        "checked"?: boolean;
        /**
          * Defines the description in the control-label.
         */
        "description"?: string;
        /**
          * Defines the `disabled` attribute of the control. If `true`, the user can not interact with the control and the controls value will not be included in the forms' data.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Defines the icon `name` inside the card. <post-banner data-size="sm"><p>If not set the icon will not show up.</p></post-banner>
         */
        "icon"?: string;
        /**
          * Defines the text in the control-label.
         */
        "label": string;
        /**
          * Defines the `name` attribute of the control. <post-banner data-size="sm"><p>This is a required property, when the control should participate in a native `form`. If not specified, a native `form` will never contain this controls value.</p></post-banner> <post-banner data-size="sm"><p>This is a required property, when the control is used with type `radio`.</p></post-banner>
         */
        "name"?: string;
        /**
          * An event emitted whenever the components checked state is toggled. The event payload (emitted under `event.detail.state`) is a boolean: `true` if the component is checked, `false` if it is unchecked. <post-banner data-size="sm"><p>If the component is used with type `radio`, it will only emit this event, when the checked state is changing to `true`.</p></post-banner>
         */
        "onPostChange"?: (event: PostCardControlCustomEvent<{ state: boolean; value: string }>) => void;
        /**
          * An event emitted whenever the components checked state is toggled. The event payload (emitted under `event.detail.state`) is a boolean: `true` if the component is checked, `false` if it is unchecked.
         */
        "onPostInput"?: (event: PostCardControlCustomEvent<{ state: boolean; value: string }>) => void;
        /**
          * Defines the `type` attribute of the control.
         */
        "type": 'checkbox' | 'radio';
        /**
          * Defines the validation `validity` of the control. To reset validity to an undefined state, simply remove the attribute from the control.
         */
        "validity"?: boolean;
        /**
          * Defines the `value` attribute of the control. <post-banner data-size="sm"><p>This is a required property, when the control is used with type `radio`.</p></post-banner>
         */
        "value"?: string;
    }
    interface PostClosebutton {
        /**
          * Overrides the close button's type ("button" by default)
          * @default 'button'
         */
        "buttonType"?: ButtonType;
    }
    interface PostCollapsible {
        /**
          * If `true`, the element is collapsed otherwise it is displayed.
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * An event emitted when the collapse element is shown or hidden, before the transition.  The event payload is a boolean: `true` if the collapsible is expanded, `false` if it is collapsed.
         */
        "onPostToggle"?: (event: PostCollapsibleCustomEvent<boolean>) => void;
    }
    interface PostCollapsibleTrigger {
        /**
          * Link the trigger to a post-collapsible with this id
         */
        "for": string;
    }
    interface PostEnvTest {
    }
    interface PostFooter {
        /**
          * The textFooter to add to the footer (visually hidden).
         */
        "textFooter": string;
    }
    interface PostHeader {
        /**
          * The label of the burger menu button.
         */
        "textMenu": string;
    }
    /**
     * @class PostIcon - representing a stencil component
     */
    interface PostIcon {
        /**
          * The name of the animation.
         */
        "animation"?: Animation;
        /**
          * The base path, where the icons are located (must be a public url).<br/>Leave this field empty to use the default cdn url.
         */
        "base"?: string;
        /**
          * When set to `true`, the icon will be flipped horizontally.
          * @default false
         */
        "flipH"?: boolean;
        /**
          * When set to `true`, the icon will be flipped vertically.
          * @default false
         */
        "flipV"?: boolean;
        /**
          * The name/id of the icon (e.g. 1000, 1001, ...).
         */
        "name": string;
        /**
          * The number of degree for the css rotate transformation.
         */
        "rotate"?: number;
        /**
          * The number for the css scale transformation.
         */
        "scale"?: number;
    }
    interface PostLanguageMenu {
        /**
          * A title for the list of language options
         */
        "textChangeLanguage": string;
        /**
          * An accessible description text for the list of language options. The `#name` placeholder is dynamic and will be replaced with the active language name.
         */
        "textCurrentLanguage": string;
        /**
          * Whether the component is rendered as a list or a menu
          * @default 'list'
         */
        "variant"?: SwitchVariant;
    }
    interface PostLanguageMenuItem {
        /**
          * If set to `true`, the language option is considered the current language for the page.
         */
        "active"?: boolean;
        /**
          * The ISO 639 language code, formatted according to [RFC 5646 (also known as BCP 47)](https://datatracker.ietf.org/doc/html/rfc5646). For example, "de".
         */
        "code": string;
        /**
          * The full name of the language. For example, "Deutsch".
         */
        "name"?: string;
        /**
          * An event emitted when the language option is clicked. The payload is the ISO 639 code of the language.
         */
        "onPostChange"?: (event: PostLanguageMenuItemCustomEvent<string>) => void;
        /**
          * An event emitted when the language option is initially active. The payload is the ISO 639 code of the language.
         */
        "onPostLanguageMenuItemInitiallyActive"?: (event: PostLanguageMenuItemCustomEvent<string>) => void;
        /**
          * The URL used for the href attribute of the internal anchor. This field is optional; if not provided, a button will be used internally instead of an anchor.
         */
        "url"?: string;
        /**
          * To communicate the variant prop from the parent (post-language-menu) component to the child (post-language-menu-item) component. See parent docs for a description about the property itself.
         */
        "variant"?: SwitchVariant;
    }
    interface PostLinkarea {
    }
    interface PostLogo {
        /**
          * The URL to which the user is redirected upon clicking the logo.
         */
        "url"?: string | URL;
    }
    interface PostMainnavigation {
        /**
          * Defines the accessible label for the navigation element. This text is used as the `aria-label` attribute to provide screen reader users with a description of the navigation's purpose.
         */
        "textMain": string;
    }
    interface PostMegadropdown {
        /**
          * Emits when the dropdown is shown or hidden. The event payload is an object. `isVisible` is true when the dropdown gets opened and false when it gets closed `focusParent` determines whether after the closing of the mega dropdown, the focus should go back to the trigger parent or naturally go to the next focusable element in the page
         */
        "onPostToggleMegadropdown"?: (event: PostMegadropdownCustomEvent<{ isVisible: boolean; focusParent?: boolean }>) => void;
        /**
          * A label for the back button visible on tablet and mobile
         */
        "textBack": string;
        /**
          * An accessible label for the close button visible on desktop
         */
        "textClose": string;
    }
    interface PostMegadropdownTrigger {
        /**
          * Sets the trigger state to be active or inactive.
          * @default false
         */
        "active"?: boolean;
        /**
          * ID of the mega dropdown element that this trigger is linked to. Used to open and close the specified mega dropdown.
         */
        "for": string;
    }
    interface PostMenu {
        /**
          * A descriptive label that clearly identifies the menu’s content so assistive technologies can convey its purpose.
         */
        "label": string;
        /**
          * Emits when the menu is shown or hidden. The event payload is a boolean: `true` when the menu was opened, `false` when it was closed.
         */
        "onToggleMenu"?: (event: PostMenuCustomEvent<boolean>) => void;
        /**
          * Defines the position of the menu relative to its trigger. Menus are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries. For supported values and behavior details, see the [Floating UI placement documentation](https://floating-ui.com/docs/computePosition#placement).
          * @default 'bottom'
         */
        "placement"?: Placement;
    }
    interface PostMenuItem {
    }
    interface PostMenuTrigger {
        /**
          * ID of the menu element that this trigger is linked to. Used to open and close the specified menu.
         */
        "for": string;
    }
    interface PostPagination {
        /**
          * The total number of items in the collection.
         */
        "collectionSize": number;
        /**
          * If true, the pagination is disabled.
         */
        "disabled"?: boolean;
        /**
          * A descriptive label for the pagination navigation, used by assistive technologies.
         */
        "label": string;
        /**
          * Event emitted when the page changes.
         */
        "onPostChange"?: (event: PostPaginationCustomEvent<number>) => void;
        /**
          * The current active page number.  **If not specified, defaults to the first page.**
         */
        "page"?: number;
        /**
          * The number of items per page.
         */
        "pageSize": number;
        /**
          * Prefix text for the first page label.
         */
        "textFirst": string;
        /**
          * Prefix text for the last page label.
         */
        "textLast": string;
        /**
          * Accessible label for the next page button.
         */
        "textNext": string;
        /**
          * Prefix text for page number labels.
         */
        "textPage": string;
        /**
          * Accessible label for the previous page button.
         */
        "textPrevious": string;
    }
    interface PostPopover {
        /**
          * Show a little indicator arrow
          * @default true
         */
        "arrow"?: boolean;
        /**
          * Defines the position of the popover relative to its trigger. Popovers are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries. For supported values and behavior details, see the [Floating UI placement documentation](https://floating-ui.com/docs/computePosition#placement).
          * @default 'top'
         */
        "placement"?: Placement;
        /**
          * Define the text of the close button for assistive technology
         */
        "textClose": string;
    }
    interface PostPopoverTrigger {
        /**
          * ID of the popover element that this trigger is linked to. Used to open and close the popover.
         */
        "for"?: string;
    }
    interface PostPopovercontainer {
        /**
          * Animation style
          * @default null
         */
        "animation"?: 'pop-in' | null;
        /**
          * Whether or not to display a little pointer arrow
          * @default false
         */
        "arrow"?: boolean;
        /**
          * Gap between the edge of the page and the popovercontainer
          * @default 8
         */
        "edgeGap"?: number;
        /**
          * Fires whenever the popovercontainer is about to be shown, passing in event.detail a `first` boolean, which is true if it is to be shown for the first time.
         */
        "onPostBeforeShow"?: (event: PostPopovercontainerCustomEvent<{ first?: boolean }>) => void;
        /**
          * Fires whenever the popovercontainer is about to be shown or hidden, passing in event.detail a `willOpen` boolean, which is true if the popovercontainer is about to be opened and false if it is about to be closed.
         */
        "onPostBeforeToggle"?: (event: PostPopovercontainerCustomEvent<{ willOpen: boolean }>) => void;
        /**
          * Fires whenever the popovercontainer is hidden.
         */
        "onPostHide"?: (event: PostPopovercontainerCustomEvent<any>) => void;
        /**
          * Fires whenever the popovercontainer is shown, passing in event.detail a `first` boolean, which is true if it is shown for the first time.
         */
        "onPostShow"?: (event: PostPopovercontainerCustomEvent<{ first?: boolean }>) => void;
        /**
          * Fires whenever the popovercontainer gets shown or hidden, passing in event.detail an object containing a `isOpen`boolean, which is true if the popovercontainer was opened and false if it was closed.
         */
        "onPostToggle"?: (event: PostPopovercontainerCustomEvent<{ isOpen: boolean }>) => void;
        /**
          * Defines the placement of the popovercontainer according to the floating-ui options available at https://floating-ui.com/docs/computePosition#placement. Popovercontainers are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries.
          * @default 'top'
         */
        "placement"?: Placement;
        /**
          * Enables a safespace through which the cursor can be moved without the popover being disabled
         */
        "safeSpace"?: 'triangle' | 'trapezoid';
    }
    interface PostRating {
        /**
          * Defines the rating that the component should show.
          * @default 0
         */
        "currentRating"?: number;
        /**
          * A hidden, descriptive label that explains the role of the rating component to assistive technologies.
         */
        "label": string;
        /**
          * An event emitted whenever the component's value has changed (on blur). The event payload can be used like so: `event.detail.value`.
         */
        "onPostChange"?: (event: PostRatingCustomEvent<{ value: number }>) => void;
        /**
          * An event emitted whenever the component's value has changed (on input). The event payload can be used like so: `event.detail.value`.
         */
        "onPostInput"?: (event: PostRatingCustomEvent<{ value: number }>) => void;
        /**
          * Defines if the component is readonly or not. This usually should be used together with the `currentRating` property.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Defines the total amount of stars rendered in the component.
          * @default 5
         */
        "stars"?: number;
    }
    interface PostStepper {
        /**
          * Defines the currently active step
          * @default -1
         */
        "currentIndex"?: number;
        /**
          * "Completed step" label for accessibility
         */
        "textCompletedStep": string;
        /**
          * "Current step" label for accessibility
         */
        "textCurrentStep": string;
        /**
          * Label for the "Step N:" indicator for mobile view. Use `#number` as a placeholder — it will be replaced with the current step number at runtime.
         */
        "textStepNumber": string;
    }
    interface PostStepperItem {
    }
    interface PostTabItem {
        /**
          * The name of the tab, used to associate it with a tab panel or identify the active tab in panel mode.
         */
        "name": string;
    }
    interface PostTabPanel {
        /**
          * The name of the tab that this panel is associated with.
         */
        "for": string;
    }
    interface PostTabs {
        /**
          * The name of the tab in the panel mode that is initially active. Changing this value after initialization has no effect. If not specified, defaults to the first tab.
         */
        "activeTab"?: string;
        /**
          * When set to true, this property allows the tabs container to span the Changing this value after initialization has no effect. full width of the screen, from edge to edge.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * The accessible label for the tabs component in navigation mode.
         */
        "label"?: string;
        /**
          * An event emitted after the active tab changes, when the fade in transition of its associated panel is finished. The payload is the name of the newly active tab. Only emitted in panel mode.
         */
        "onPostChange"?: (event: PostTabsCustomEvent<string>) => void;
    }
    interface PostTogglebutton {
        /**
          * If `true`, the button is in the "on" state, otherwise it is in the "off" state.
          * @default false
         */
        "toggled"?: boolean;
    }
    interface PostTooltip {
        /**
          * Choose a tooltip animation
         */
        "animation"?: 'pop-in';
        /**
          * Whether or not to display a little pointer arrow
          * @default false
         */
        "arrow"?: boolean;
        /**
          * Indicates the open state of the tooltip
          * @default false
         */
        "open"?: boolean;
        /**
          * Defines the position of the tooltip relative to its trigger. Tooltips are automatically flipped to the opposite side if there is not enough available space and are shifted towards the viewport if they would overlap edge boundaries. For supported values and behavior details, see the [Floating UI placement documentation](https://floating-ui.com/docs/computePosition#placement).
          * @default 'top'
         */
        "placement"?: Placement;
    }
    interface PostTooltipTrigger {
        /**
          * Delay (in milliseconds) before the tooltip is shown.
          * @default 0
         */
        "delay"?: number;
        /**
          * ID of the tooltip element that this trigger is linked to.
         */
        "for": string;
    }
    interface IntrinsicElements {
        "post-accordion": PostAccordion;
        "post-accordion-item": PostAccordionItem;
        "post-avatar": PostAvatar;
        "post-back-to-top": PostBackToTop;
        "post-banner": PostBanner;
        "post-breadcrumb-item": PostBreadcrumbItem;
        "post-breadcrumbs": PostBreadcrumbs;
        "post-card-control": PostCardControl;
        "post-closebutton": PostClosebutton;
        "post-collapsible": PostCollapsible;
        "post-collapsible-trigger": PostCollapsibleTrigger;
        "post-env-test": PostEnvTest;
        "post-footer": PostFooter;
        "post-header": PostHeader;
        "post-icon": PostIcon;
        "post-language-menu": PostLanguageMenu;
        "post-language-menu-item": PostLanguageMenuItem;
        "post-linkarea": PostLinkarea;
        "post-logo": PostLogo;
        "post-mainnavigation": PostMainnavigation;
        "post-megadropdown": PostMegadropdown;
        "post-megadropdown-trigger": PostMegadropdownTrigger;
        "post-menu": PostMenu;
        "post-menu-item": PostMenuItem;
        "post-menu-trigger": PostMenuTrigger;
        "post-pagination": PostPagination;
        "post-popover": PostPopover;
        "post-popover-trigger": PostPopoverTrigger;
        "post-popovercontainer": PostPopovercontainer;
        "post-rating": PostRating;
        "post-stepper": PostStepper;
        "post-stepper-item": PostStepperItem;
        "post-tab-item": PostTabItem;
        "post-tab-panel": PostTabPanel;
        "post-tabs": PostTabs;
        "post-togglebutton": PostTogglebutton;
        "post-tooltip": PostTooltip;
        "post-tooltip-trigger": PostTooltipTrigger;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "post-accordion": LocalJSX.PostAccordion & JSXBase.HTMLAttributes<HTMLPostAccordionElement>;
            "post-accordion-item": LocalJSX.PostAccordionItem & JSXBase.HTMLAttributes<HTMLPostAccordionItemElement>;
            "post-avatar": LocalJSX.PostAvatar & JSXBase.HTMLAttributes<HTMLPostAvatarElement>;
            "post-back-to-top": LocalJSX.PostBackToTop & JSXBase.HTMLAttributes<HTMLPostBackToTopElement>;
            "post-banner": LocalJSX.PostBanner & JSXBase.HTMLAttributes<HTMLPostBannerElement>;
            "post-breadcrumb-item": LocalJSX.PostBreadcrumbItem & JSXBase.HTMLAttributes<HTMLPostBreadcrumbItemElement>;
            "post-breadcrumbs": LocalJSX.PostBreadcrumbs & JSXBase.HTMLAttributes<HTMLPostBreadcrumbsElement>;
            /**
             * @class PostCardControl - representing a stencil component
             */
            "post-card-control": LocalJSX.PostCardControl & JSXBase.HTMLAttributes<HTMLPostCardControlElement>;
            "post-closebutton": LocalJSX.PostClosebutton & JSXBase.HTMLAttributes<HTMLPostClosebuttonElement>;
            "post-collapsible": LocalJSX.PostCollapsible & JSXBase.HTMLAttributes<HTMLPostCollapsibleElement>;
            "post-collapsible-trigger": LocalJSX.PostCollapsibleTrigger & JSXBase.HTMLAttributes<HTMLPostCollapsibleTriggerElement>;
            "post-env-test": LocalJSX.PostEnvTest & JSXBase.HTMLAttributes<HTMLPostEnvTestElement>;
            "post-footer": LocalJSX.PostFooter & JSXBase.HTMLAttributes<HTMLPostFooterElement>;
            "post-header": LocalJSX.PostHeader & JSXBase.HTMLAttributes<HTMLPostHeaderElement>;
            /**
             * @class PostIcon - representing a stencil component
             */
            "post-icon": LocalJSX.PostIcon & JSXBase.HTMLAttributes<HTMLPostIconElement>;
            "post-language-menu": LocalJSX.PostLanguageMenu & JSXBase.HTMLAttributes<HTMLPostLanguageMenuElement>;
            "post-language-menu-item": LocalJSX.PostLanguageMenuItem & JSXBase.HTMLAttributes<HTMLPostLanguageMenuItemElement>;
            "post-linkarea": LocalJSX.PostLinkarea & JSXBase.HTMLAttributes<HTMLPostLinkareaElement>;
            "post-logo": LocalJSX.PostLogo & JSXBase.HTMLAttributes<HTMLPostLogoElement>;
            "post-mainnavigation": LocalJSX.PostMainnavigation & JSXBase.HTMLAttributes<HTMLPostMainnavigationElement>;
            "post-megadropdown": LocalJSX.PostMegadropdown & JSXBase.HTMLAttributes<HTMLPostMegadropdownElement>;
            "post-megadropdown-trigger": LocalJSX.PostMegadropdownTrigger & JSXBase.HTMLAttributes<HTMLPostMegadropdownTriggerElement>;
            "post-menu": LocalJSX.PostMenu & JSXBase.HTMLAttributes<HTMLPostMenuElement>;
            "post-menu-item": LocalJSX.PostMenuItem & JSXBase.HTMLAttributes<HTMLPostMenuItemElement>;
            "post-menu-trigger": LocalJSX.PostMenuTrigger & JSXBase.HTMLAttributes<HTMLPostMenuTriggerElement>;
            "post-pagination": LocalJSX.PostPagination & JSXBase.HTMLAttributes<HTMLPostPaginationElement>;
            "post-popover": LocalJSX.PostPopover & JSXBase.HTMLAttributes<HTMLPostPopoverElement>;
            "post-popover-trigger": LocalJSX.PostPopoverTrigger & JSXBase.HTMLAttributes<HTMLPostPopoverTriggerElement>;
            "post-popovercontainer": LocalJSX.PostPopovercontainer & JSXBase.HTMLAttributes<HTMLPostPopovercontainerElement>;
            "post-rating": LocalJSX.PostRating & JSXBase.HTMLAttributes<HTMLPostRatingElement>;
            "post-stepper": LocalJSX.PostStepper & JSXBase.HTMLAttributes<HTMLPostStepperElement>;
            "post-stepper-item": LocalJSX.PostStepperItem & JSXBase.HTMLAttributes<HTMLPostStepperItemElement>;
            "post-tab-item": LocalJSX.PostTabItem & JSXBase.HTMLAttributes<HTMLPostTabItemElement>;
            "post-tab-panel": LocalJSX.PostTabPanel & JSXBase.HTMLAttributes<HTMLPostTabPanelElement>;
            "post-tabs": LocalJSX.PostTabs & JSXBase.HTMLAttributes<HTMLPostTabsElement>;
            "post-togglebutton": LocalJSX.PostTogglebutton & JSXBase.HTMLAttributes<HTMLPostTogglebuttonElement>;
            "post-tooltip": LocalJSX.PostTooltip & JSXBase.HTMLAttributes<HTMLPostTooltipElement>;
            "post-tooltip-trigger": LocalJSX.PostTooltipTrigger & JSXBase.HTMLAttributes<HTMLPostTooltipTriggerElement>;
        }
    }
}
