name: Component v2
description: Add a working item for a component targeted at the new Design v2
title: '[component]: '
labels: ['📦 components', 'needs:refinement']
projects: ['swisspost/3']
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A short description of the component, disambiguation if needed
      placeholder: A tooltip shows short, additional information on focusable elements.
    validations:
      required: false
  - type: input
    id: designurl
    attributes:
      label: Design
      description: Link to the component in Figma
    validations:
      required: true
  - type: checkboxes
    id: tokens
    attributes:
      label: Tokens
      description: Indicates whether tokens already exist for this component
      options:
        - label: Tokens for this component are ready
  - type: textarea
    id: tasksdesign
    attributes:
      label: Tasks design
      description: Default tasks for the design team. Can be edited later according to needs.
      value: |
        ```[tasklist]
        ### 🎨 Design
        - [ ] Design component according to WIKIT
        - [ ] Update dependencies
        - [ ] Add & test compo in layout examples
        - [ ] Designer review
        - [ ] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
        - [ ] Documentation: Technical documentation (Anatomy, accessibility)
        - [ ] Documentation: Review (content correctness, understandability, gaps)
        ```
  - type: textarea
    id: tasksdev
    attributes:
      label: Tasks development
      description: Default tasks for the dev team. Can be edited later according to needs.
      value: |
        ```[tasklist]
        ### 💻 Tasks development
        - [ ] Review Design (All states present? Possible to implement?)
        - [ ] Tokenization
        - [ ] HTML/CSS implementation
        - [ ] Web component implementation
        - [ ] Documentation in Storybook
        - [ ] Unit tests
        - [ ] End to end tests
        - [ ] Visual regression tests
        - [ ] Design review
        ```
