// main.ts
import { defineCustomElements, setNonce } from '@swisspsot/design-system-components/loader';

// Will set the `nonce` attribute for all script tags
// i.e. will run scriptTag.setAttribute('nonce', 'r4nd0m')
// Obviously, you should use the nonce generated by your server
setNonce('r4nd0m');
defineCustomElements();
