###
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
###

name: Artifact Upload
description: Uploads an entire artifact folder to share data between jobs and store data once a workflow is complete.

inputs:
  name:
    description: Name of the artifact
    required: true
    type: string
  folder:
    description: Path to the folder to upload
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Validate folder exists
      env:
        FOLDER: ${{ inputs.folder }}
      shell: bash
      run: |
        if [[ ! -d "$FOLDER" ]]; then
          echo "Error: Folder $FOLDER does not exist"
          exit 1
        fi

    - name: Save Event Infos into the artifact folder
      env:
        FOLDER: ${{ inputs.folder }}
      shell: bash
      run: |
        if ! [[ "${{ github.event.number }}" =~ ^[0-9]*$ ]]; then
          echo "Warning: Invalid event number format, using default"
          echo "0" > $FOLDER/GHA-EVENT-ID
        else
          echo "${{ github.event.number }}" > $FOLDER/GHA-EVENT-ID
        fi

        ACTION="${{ github.event.action }}"
        SANITIZED_ACTION=$(echo "$ACTION" | tr -cd '[:alnum:]-_')
        echo "$SANITIZED_ACTION" > $FOLDER/GHA-EVENT-ACTION

    - name: Zip artifact folder
      env:
        FOLDER: ${{ inputs.folder }}
      shell: bash
      run: cd $FOLDER && zip artifacts.zip . -r

    - name: Upload artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.folder }}/artifacts.zip
