###
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
###

name: Artifact Upload
description: Uploads an entire artifact folder to share data between jobs and store data once a workflow is complete.

inputs:
  name:
    description: Name of the artifact
    required: true
    type: string
  folder:
    description: Path to the folder to upload
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Validate folder exists
      shell: bash
      run: |
        if [[ ! -d "${{ inputs.folder }}" ]]; then
          echo "Error: Folder ${{ inputs.folder }} does not exist"
          exit 1
        fi

    - name: Save Event Infos into the artifact folder
      shell: bash
      run: |
        if ! [[ "${{ github.event.number }}" =~ ^[0-9]*$ ]]; then
          echo "Warning: Invalid event number format, using default"
          echo "0" > ${{ inputs.folder }}/GHA-EVENT-ID
        else
          echo "${{ github.event.number }}" > ${{ inputs.folder }}/GHA-EVENT-ID
        fi
        
        ACTION="${{ github.event.action }}"
        SANITIZED_ACTION=$(echo "$ACTION" | tr -cd '[:alnum:]-_')
        echo "$SANITIZED_ACTION" > ${{ inputs.folder }}/GHA-EVENT-ACTION

    - name: Zip artifact folder
      shell: bash
      run: cd ${{ inputs.folder }} && zip artifacts.zip . -r

    - name: Upload artifacts
      uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.folder }}/artifacts.zip
