import { loadTranslations } from '@angular/localize';

const I18N_VALUES = {
  de: {
    'ngb.alert.close': 'Schließen',
    'ngb.timepicker.HH': 'HH',
    'ngb.toast.close-aria': 'Schließen',
    'ngb.pagination.first': '««',
    'ngb.datepicker.select-month': 'Monat auswählen',
    'ngb.datepicker.previous-month': 'Vorheriger Monat',
    'ngb.progressbar.value': '{$INTERPOLATION}',
    'ngb.carousel.slide-number': ' Folie {$INTERPOLATION} von {$INTERPOLATION_1} ',
    'ngb.timepicker.hours': 'Stunden',
    'ngb.pagination.previous': '«',
    'ngb.carousel.previous': 'Vorherige',
    'ngb.timepicker.MM': 'MM',
    'ngb.pagination.next': '»',
    'ngb.datepicker.select-year': 'Jahr auswählen',
    'ngb.datepicker.next-month': 'Nächster Monat',
    'ngb.carousel.next': 'Nächste',
    'ngb.timepicker.minutes': 'Minuten',
    'ngb.pagination.last': '»»',
    'ngb.timepicker.increment-hours': 'Stunden erhöhen',
    'ngb.pagination.first-aria': 'Erster',
    'ngb.pagination.previous-aria': 'Vorheriger',
    'ngb.timepicker.decrement-hours': 'Stunden verringern',
    'ngb.pagination.next-aria': 'Nächster',
    'ngb.timepicker.increment-minutes': 'Minuten erhöhen',
    'ngb.pagination.last-aria': 'Letzter',
    'ngb.timepicker.decrement-minutes': 'Minuten verringern',
    'ngb.timepicker.SS': 'SS',
    'ngb.timepicker.seconds': 'Sekunden',
    'ngb.timepicker.increment-seconds': 'Sekunden erhöhen',
    'ngb.timepicker.decrement-seconds': 'Sekunden verringern',
    'ngb.timepicker.PM': '{$INTERPOLATION}',
    'ngb.timepicker.AM': '{$INTERPOLATION}',
  },
  fr: {
    'ngb.alert.close': 'Fermer',
    'ngb.timepicker.HH': 'HH',
    'ngb.toast.close-aria': 'Fermer',
    'ngb.pagination.first': '««',
    'ngb.datepicker.select-month': 'Sélectionner le mois',
    'ngb.datepicker.previous-month': 'Mois précédent',
    'ngb.progressbar.value': '{$INTERPOLATION}',
    'ngb.carousel.slide-number': ' Diapositive {$INTERPOLATION} sur {$INTERPOLATION_1} ',
    'ngb.timepicker.hours': 'Heures',
    'ngb.pagination.previous': '«',
    'ngb.carousel.previous': 'Précédent',
    'ngb.timepicker.MM': 'MM',
    'ngb.pagination.next': '»',
    'ngb.datepicker.select-year': "Sélectionner l'année",
    'ngb.datepicker.next-month': 'Mois suivant',
    'ngb.carousel.next': 'Suivant',
    'ngb.timepicker.minutes': 'Minutes',
    'ngb.pagination.last': '»»',
    'ngb.timepicker.increment-hours': 'Incrémenter les heures',
    'ngb.pagination.first-aria': 'Premier',
    'ngb.pagination.previous-aria': 'Précédent',
    'ngb.timepicker.decrement-hours': 'Décrémenter les heures',
    'ngb.pagination.next-aria': 'Suivant',
    'ngb.timepicker.increment-minutes': 'Incrémenter les minutes',
    'ngb.pagination.last-aria': 'Dernier',
    'ngb.timepicker.decrement-minutes': 'Décrémenter les minutes',
    'ngb.timepicker.SS': 'SS',
    'ngb.timepicker.seconds': 'Secondes',
    'ngb.timepicker.increment-seconds': 'Incrémenter les secondes',
    'ngb.timepicker.decrement-seconds': 'Décrémenter les secondes',
    'ngb.timepicker.PM': '{$INTERPOLATION}',
    'ngb.timepicker.AM': '{$INTERPOLATION}',
  },
  it: {
    'ngb.alert.close': 'Chiudi',
    'ngb.timepicker.HH': 'HH',
    'ngb.toast.close-aria': 'Chiudi',
    'ngb.pagination.first': '««',
    'ngb.datepicker.select-month': 'Seleziona il mese',
    'ngb.datepicker.previous-month': 'Mese precedente',
    'ngb.progressbar.value': '{$INTERPOLATION}',
    'ngb.carousel.slide-number': ' Diapositiva {$INTERPOLATION} di {$INTERPOLATION_1} ',
    'ngb.timepicker.hours': 'Ore',
    'ngb.pagination.previous': '«',
    'ngb.carousel.previous': 'Precedente',
    'ngb.timepicker.MM': 'MM',
    'ngb.pagination.next': '»',
    'ngb.datepicker.select-year': "Seleziona l'anno",
    'ngb.datepicker.next-month': 'Mese successivo',
    'ngb.carousel.next': 'Successivo',
    'ngb.timepicker.minutes': 'Minuti',
    'ngb.pagination.last': '»»',
    'ngb.timepicker.increment-hours': 'Incrementa le ore',
    'ngb.pagination.first-aria': 'Primo',
    'ngb.pagination.previous-aria': 'Precedente',
    'ngb.timepicker.decrement-hours': 'Decrementa le ore',
    'ngb.pagination.next-aria': 'Successivo',
    'ngb.timepicker.increment-minutes': 'Incrementa i minuti',
    'ngb.pagination.last-aria': 'Ultimo',
    'ngb.timepicker.decrement-minutes': 'Decrementa i minuti',
    'ngb.timepicker.SS': 'SS',
    'ngb.timepicker.seconds': 'Secondi',
    'ngb.timepicker.increment-seconds': 'Incrementa i secondi',
    'ngb.timepicker.decrement-seconds': 'Decrementa i secondi',
    'ngb.timepicker.PM': '{$INTERPOLATION}',
    'ngb.timepicker.AM': '{$INTERPOLATION}',
  },
  en: {
    'ngb.alert.close': 'Close',
    'ngb.timepicker.HH': 'HH',
    'ngb.toast.close-aria': 'Close',
    'ngb.pagination.first': '««',
    'ngb.datepicker.select-month': 'Select month',
    'ngb.datepicker.previous-month': 'Previous month',
    'ngb.progressbar.value': '{$INTERPOLATION}',
    'ngb.carousel.slide-number': ' Slide {$INTERPOLATION} of {$INTERPOLATION_1} ',
    'ngb.timepicker.hours': 'Hours',
    'ngb.pagination.previous': '«',
    'ngb.carousel.previous': 'Previous',
    'ngb.timepicker.MM': 'MM',
    'ngb.pagination.next': '»',
    'ngb.datepicker.select-year': 'Select year',
    'ngb.datepicker.next-month': 'Next month',
    'ngb.carousel.next': 'Next',
    'ngb.timepicker.minutes': 'Minutes',
    'ngb.pagination.last': '»»',
    'ngb.timepicker.increment-hours': 'Increment hours',
    'ngb.pagination.first-aria': 'First',
    'ngb.pagination.previous-aria': 'Previous',
    'ngb.timepicker.decrement-hours': 'Decrement hours',
    'ngb.pagination.next-aria': 'Next',
    'ngb.timepicker.increment-minutes': 'Increment minutes',
    'ngb.pagination.last-aria': 'Last',
    'ngb.timepicker.decrement-minutes': 'Decrement minutes',
    'ngb.timepicker.SS': 'SS',
    'ngb.timepicker.seconds': 'Seconds',
    'ngb.timepicker.increment-seconds': 'Increment seconds',
    'ngb.timepicker.decrement-seconds': 'Decrement seconds',
    'ngb.timepicker.PM': '{$INTERPOLATION}',
    'ngb.timepicker.AM': '{$INTERPOLATION}',
  },
};

// use this function where your application's locale is initialized
loadTranslations(I18N_VALUES[localeId]);
