name: 'Dry Run Publish'
description: 'Performs a dry run of the publish process to validate package configurations.'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node & pnpm
      uses: ./.github/actions/setup-pnpm

    - name: Install & build Dependencies
      run: pnpm bootstrap
      shell: bash

    - name: Test publish step
      run: pnpm -r publish --dry-run
      shell: bash
