###
#
# If you need to do some changes in a local-action used in this
# workflow, make sure you change the action-flag to your working
# branch-name to get the latest action functionality.
#
# Example: swisspost/design-system/.github/actions/setup-environment-pnpm@my-working-branch-name
#
# Don't forget to change the action-flag back to 'main',
# once you have finished your work on the local-action!
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
###

name: Artifact Download
description: Downloads an artifact to a specific folder.

inputs:
  artifact_name:
    description: Name of the artifact
    required: true
    type: string
  artifact_folder:
    description: Path to the folder where to download to
    required: true
    type: string

outputs:
  folder:
    description: Path to the folder where to download to
    value: ${{ inputs.artifact_folder }}
  github_event_number:
    description: The github.event property from the artifact uploading workflow.
    value: ${{ steps.github_event.outputs.number }}
  github_event_action:
    description: The github.event property, from the artifact uploading workflow.
    value: ${{ steps.github_event.outputs.action }}

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_folder }}
        run_id: ${{ github.event.workflow_run.id }}
        workflow_conclusion: success
    - name: Create GithubEvent outputs
      id: github_event
      shell: bash
      run: |
        echo "::set-output name=number::$(cat ${{ inputs.artifact_folder }}/GHA-EVENT-NUMBER)"
        echo "::set-output name=action::$(cat ${{ inputs.artifact_folder }}/GHA-EVENT-ACTION)"
