###
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
###

name: Artifact Download
description: Downloads an artifact to a specific folder.

inputs:
  name:
    description: Name of the artifact
    required: true
    type: string
  folder:
    description: Path to the folder where to download to
    required: true
    type: string

outputs:
  id:
    description: The build id from the artifact uploading workflow.
    value: ${{ steps.build.outputs.id }}
  action:
    description: The build action from the artifact uploading workflow.
    value: ${{ steps.build.outputs.action }}
  folder:
    description: Path to the folder where to download to
    value: ${{ inputs.folder }}

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@07ab29fd4a977ae4d2b275087cf67563dfdf0295
      with:
        name: ${{ inputs.name }}
        run_id: ${{ github.event.workflow_run.id }}
        workflow_conclusion: success

    - name: Secure Artifact Extraction
      run: mkdir -p ${{ runner.temp }}/artifacts/

    - name: Unzip artifacts to secure directory
      run: unzip artifacts.zip -d ${{ runner.temp }}/artifacts/

    - name: Clean up
      run: rm -r artifacts.zip

    - name: Create outputs
      id: build
      run: |
        echo "id=$(cat ${{ runner.temp }}/artifacts/GHA-EVENT-ID)" >> $GITHUB_OUTPUT
        echo "action=$(cat ${{ runner.temp }}/artifacts/GHA-EVENT-ACTION)" >> $GITHUB_OUTPUT
        echo "folder=${{ runner.temp }}/artifacts" >> $GITHUB_OUTPUT
