/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ILoginWidgetOptions } from "./models/login-widget-options.model";
import { Environment } from "./models/general.model";
export { ILoginWidgetOptions } from "./models/login-widget-options.model";
export { Environment } from "./models/general.model";
export namespace Components {
    interface PostKlpLoginWidget {
        /**
          * Replaces `state.localizedConfig.header.loginWidgetOptions` from internet-header v9. Accepts a JSON string so the widget can be driven from plain HTML.
         */
        "config"?: ILoginWidgetOptions | string;
        /**
          * Replaces `state.environment` from internet-header v9.
         */
        "environment"?: Environment;
        /**
          * Replaces `state.localizedConfig.header.translations.loginWidgetText` from internet-header v9.
          * @default 'Login'
         */
        "jobsLoginText": string;
        /**
          * Overrides the logout-url provided by the portal config.
         */
        "logoutUrl"?: string;
        /**
          * Overrides the self-admin origin for menu links.
         */
        "selfAdminOrigin"?: string;
        /**
          * Sets the focus on the login button
         */
        "setFocus": () => Promise<void>;
        /**
          * Replaces `state.localizedConfig.header.showJobsLoginWidget` from internet-header v9.
          * @default false
         */
        "showJobsLoginWidget": boolean;
    }
    /**
     * Shell that only exists to reproduce the DOM shape the legacy widget walks in
     * `selectFromShadowDom()`: swisspost-internet-header -> shadowRoot -> post-klp-login-widget.
     * Renaming it breaks the legacy code, so the tag name is load-bearing.
     */
    interface SwisspostInternetHeader {
        "config"?: ILoginWidgetOptions | string;
        "environment"?: Environment;
        /**
          * @default 'Login'
         */
        "jobsLoginText": string;
        "logoutUrl"?: string;
        "selfAdminOrigin"?: string;
        /**
          * @default false
         */
        "showJobsLoginWidget": boolean;
    }
}
declare global {
    interface HTMLPostKlpLoginWidgetElement extends Components.PostKlpLoginWidget, HTMLStencilElement {
    }
    var HTMLPostKlpLoginWidgetElement: {
        prototype: HTMLPostKlpLoginWidgetElement;
        new (): HTMLPostKlpLoginWidgetElement;
    };
    /**
     * Shell that only exists to reproduce the DOM shape the legacy widget walks in
     * `selectFromShadowDom()`: swisspost-internet-header -> shadowRoot -> post-klp-login-widget.
     * Renaming it breaks the legacy code, so the tag name is load-bearing.
     */
    interface HTMLSwisspostInternetHeaderElement extends Components.SwisspostInternetHeader, HTMLStencilElement {
    }
    var HTMLSwisspostInternetHeaderElement: {
        prototype: HTMLSwisspostInternetHeaderElement;
        new (): HTMLSwisspostInternetHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "post-klp-login-widget": HTMLPostKlpLoginWidgetElement;
        "swisspost-internet-header": HTMLSwisspostInternetHeaderElement;
    }
}
declare namespace LocalJSX {
    interface PostKlpLoginWidget {
        /**
          * Replaces `state.localizedConfig.header.loginWidgetOptions` from internet-header v9. Accepts a JSON string so the widget can be driven from plain HTML.
         */
        "config"?: ILoginWidgetOptions | string;
        /**
          * Replaces `state.environment` from internet-header v9.
         */
        "environment"?: Environment;
        /**
          * Replaces `state.localizedConfig.header.translations.loginWidgetText` from internet-header v9.
          * @default 'Login'
         */
        "jobsLoginText"?: string;
        /**
          * Overrides the logout-url provided by the portal config.
         */
        "logoutUrl"?: string;
        /**
          * Overrides the self-admin origin for menu links.
         */
        "selfAdminOrigin"?: string;
        /**
          * Replaces `state.localizedConfig.header.showJobsLoginWidget` from internet-header v9.
          * @default false
         */
        "showJobsLoginWidget"?: boolean;
    }
    /**
     * Shell that only exists to reproduce the DOM shape the legacy widget walks in
     * `selectFromShadowDom()`: swisspost-internet-header -> shadowRoot -> post-klp-login-widget.
     * Renaming it breaks the legacy code, so the tag name is load-bearing.
     */
    interface SwisspostInternetHeader {
        "config"?: ILoginWidgetOptions | string;
        "environment"?: Environment;
        /**
          * @default 'Login'
         */
        "jobsLoginText"?: string;
        "logoutUrl"?: string;
        "selfAdminOrigin"?: string;
        /**
          * @default false
         */
        "showJobsLoginWidget"?: boolean;
    }

    interface PostKlpLoginWidgetAttributes {
        "config": ILoginWidgetOptions | string;
        "environment": Environment;
        "showJobsLoginWidget": boolean;
        "jobsLoginText": string;
        "logoutUrl": string;
        "selfAdminOrigin": string;
    }
    interface SwisspostInternetHeaderAttributes {
        "config": ILoginWidgetOptions | string;
        "environment": Environment;
        "showJobsLoginWidget": boolean;
        "jobsLoginText": string;
        "logoutUrl": string;
        "selfAdminOrigin": string;
    }

    interface IntrinsicElements {
        "post-klp-login-widget": Omit<PostKlpLoginWidget, keyof PostKlpLoginWidgetAttributes> & { [K in keyof PostKlpLoginWidget & keyof PostKlpLoginWidgetAttributes]?: PostKlpLoginWidget[K] } & { [K in keyof PostKlpLoginWidget & keyof PostKlpLoginWidgetAttributes as `attr:${K}`]?: PostKlpLoginWidgetAttributes[K] } & { [K in keyof PostKlpLoginWidget & keyof PostKlpLoginWidgetAttributes as `prop:${K}`]?: PostKlpLoginWidget[K] };
        "swisspost-internet-header": Omit<SwisspostInternetHeader, keyof SwisspostInternetHeaderAttributes> & { [K in keyof SwisspostInternetHeader & keyof SwisspostInternetHeaderAttributes]?: SwisspostInternetHeader[K] } & { [K in keyof SwisspostInternetHeader & keyof SwisspostInternetHeaderAttributes as `attr:${K}`]?: SwisspostInternetHeaderAttributes[K] } & { [K in keyof SwisspostInternetHeader & keyof SwisspostInternetHeaderAttributes as `prop:${K}`]?: SwisspostInternetHeader[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "post-klp-login-widget": LocalJSX.IntrinsicElements["post-klp-login-widget"] & JSXBase.HTMLAttributes<HTMLPostKlpLoginWidgetElement>;
            /**
             * Shell that only exists to reproduce the DOM shape the legacy widget walks in
             * `selectFromShadowDom()`: swisspost-internet-header -> shadowRoot -> post-klp-login-widget.
             * Renaming it breaks the legacy code, so the tag name is load-bearing.
             */
            "swisspost-internet-header": LocalJSX.IntrinsicElements["swisspost-internet-header"] & JSXBase.HTMLAttributes<HTMLSwisspostInternetHeaderElement>;
        }
    }
}
