import { createClassUpdateRuleWrapper } from '../../../utils/create-class-update-rule';

// Css class names
const classNames: string[] = [
  '.valid-tooltip',
  '.invalid-tooltip',
  '.form-control-sm',
  '.form-control-rg',
  '.form-control-lg',
  '.form-select-sm',
  '.form-select-rg',
  '.form-select-lg',
  '.vertical-gutters',
  '.border-gutters',
  '.container-reset',
  '.container-reset-left',
  '.container-reset-right',
  '.container-fluid-xs',
  '.container-fluid-sm',
  '.container-fluid-rg',
  '.container-fluid-md',
  '.container-fluid-lg',
  '.container-fluid-xl',
  '.container-fluid-xxl',

  '.bg-yellow',
  '.bg-white',
  '.bg-light',
  '.bg-gray',
  '.bg-dark',
  '.bg-black',
  '.bg-primary',
  '.bg-secondary',
  '.bg-success',
  '.bg-warning',
  '.bg-error',
  '.bg-info',
  '.bg-success-background',
  '.bg-warning-background',
  '.bg-error-background',
  '.bg-nightblue',
  '.bg-nightblue-bright',
  '.bg-petrol',
  '.bg-petrol-bright',
  '.bg-coral',
  '.bg-coral-bright',
  '.bg-olive',
  '.bg-olive-bright',
  '.bg-purple',
  '.bg-purple-bright',
  '.bg-aubergine',
  '.bg-aubergine-bright',

  '.lh-hair',
  '.lh-line',
  '.lh-micro',
  '.lh-mini',
  '.lh-small-regular',
  '.lh-regular',
  '.lh-small-large',
  '.lh-large',
  '.lh-big',
  '.lh-bigger-big',
  '.lh-small-huge',
  '.lh-huge',
  '.lh-small-giant',
  '.lh-giant',
  '.lh-bigger-giant',

  '.text-primary',
  '.text-secondary',
  '.text-light',
  '.text-dark',
  '.text-success',
  '.text-warning',
  '.text-error',
  '.text-info',

  '.spacer',
  '.h-visuallyhidden-up-md',
  '.h-visuallyhidden-down-rg',
  '.h-visuallyhidden-down-lg',

  '.fw-light',
  '.light',
  '.lh-base',
  '.font-monospace',

  '.card-button',
  '.card-buttons',
  '.btn-animated',
  '.breadcrumb-item',
  '.alert-fixed-bottom',
  '.card-group',
  '.chip-sm',

  '.btn-nightblue',
  '.btn-nightblue-bright',
  '.btn-petrol',
  '.btn-petrol-bright',
  '.btn-coral',
  '.btn-coral-bright',
  '.btn-olive',
  '.btn-olive-bright',
  '.btn-purple',
  '.btn-purple-bright',
  '.btn-aubergine',
  '.btn-aubergine-bright',
];

export const classesMap = classNames.map(selector => ({
  old: selector.slice(1).replace(/\./g, ' '),
  new: '',
}));

export const { name, rule } = createClassUpdateRuleWrapper({
  name: 'no-deprecated-css-classes',
  type: 'problem',
  description: 'Flags deprecated CSS classes and removes them.',
  classesMap,
});

export default rule;
