import {
  AttachInternals,
  Component,
  Element,
  Event,
  EventEmitter,
  h,
  Host,
  Listen,
  Method,
  Prop,
  State,
  Watch,
} from '@stencil/core';
import { checkEmptyOrType } from '@/utils';
import { version } from '@root/package.json';
import {
  autoUpdate,
  computePosition,
  flip,
  offset,
  size,
} from '@floating-ui/dom';

// Use native HTMLPostListboxElement type generated by Stencil
type PostListboxElement = HTMLPostListboxElement;

/**
 * @class PostAutocomplete - A combobox component that provides autocomplete functionality.
 *
 * @slot default - Content slot for input, label, hints, validation messages, and a nested post-listbox.
 */
@Component({
  tag: 'post-autocomplete',
  styleUrl: 'post-autocomplete.scss',
  shadow: true,
  formAssociated: true,
})
export class PostAutocomplete {
  private inputElement: HTMLInputElement | null = null;
  private listboxElement: PostListboxElement | null = null;
  private liveRegionElement: HTMLElement | null = null;
  private clearAutoUpdate: (() => void) | null = null;

  @Element() host: HTMLElement;

  @AttachInternals() private internals: ElementInternals;

  /**
   * Whether the listbox is currently open.
   */
  @State() isOpen = false;

  /**
   * The current active descendant option ID for ARIA.
   */
  @State() activeDescendantId: string | null = null;

  /**
   * The current input value.
   */
  @State() inputValue = '';

  /**
   * The number of visible options after filtering.
   */
  @State() visibleOptionCount = 0;

  /**
   * The minimum number of characters required before filtering begins.
   * Set to 0 to show all options immediately when the input is focused.
   */
  @Prop({ reflect: true, attribute: 'filter-threshold' }) filterThreshold = 0;

  /**
   * Whether to show a clear button when there is input.
   */
  @Prop({ reflect: true }) clearable = false;

  /**
   * The name of the form control, used when submitting forms.
   */
  @Prop({ reflect: true }) name?: string;

  /**
   * The current value of the autocomplete.
   */
  @Prop({ mutable: true, reflect: true }) value?: string;

  /**
   * Whether the autocomplete is disabled.
   */
  @Prop({ reflect: true }) disabled = false;

  /**
   * Whether the autocomplete is required.
   */
  @Prop({ reflect: true }) required = false;

  /**
   * Placeholder text for the input.
   */
  @Prop() placeholder?: string;

  /**
   * Message shown when no options match the filter.
   */
  @Prop({ attribute: 'no-results-text' }) noResultsText = 'No results found';

  /**
   * Emitted when a filter request is made. The event is cancellable.
   * If cancelled, the default filtering behavior is skipped.
   */
  @Event() postFilterRequest: EventEmitter<{ query: string }>;

  /**
   * Emitted when the value changes (an option is selected).
   */
  @Event() postChange: EventEmitter<{ value: string; label: string }>;

  /**
   * Emitted when the input value changes (typing).
   */
  @Event() postInput: EventEmitter<{ value: string }>;

  @Watch('filterThreshold')
  validateFilterThreshold() {
    checkEmptyOrType(this, 'filterThreshold', 'number');
  }

  @Watch('value')
  handleValueChange(newValue: string) {
    this.internals.setFormValue(newValue || null);
  }

  @Listen('postListboxChange')
  handleListboxChange(event: CustomEvent<{ value: string; label: string }>) {
    const { value, label } = event.detail;
    this.value = value;
    this.inputValue = label;

    if (this.inputElement) {
      this.inputElement.value = label;
    }

    this.internals.setFormValue(value);
    this.postChange.emit({ value, label });
    this.closeListbox();
  }

  @Listen('postListboxFilterComplete')
  handleFilterComplete(event: CustomEvent<{ count: number }>) {
    this.visibleOptionCount = event.detail.count;
    this.announceResults(event.detail.count);
  }

  /**
   * Opens the listbox dropdown.
   */
  @Method()
  async open(): Promise<void> {
    if (this.disabled || this.isOpen) return;
    await this.openListbox();
  }

  /**
   * Closes the listbox dropdown.
   */
  @Method()
  async close(): Promise<void> {
    if (!this.isOpen) return;
    this.closeListbox();
  }

  /**
   * Clears the current value and input.
   */
  @Method()
  async clear(): Promise<void> {
    this.value = '';
    this.inputValue = '';
    if (this.inputElement) {
      this.inputElement.value = '';
    }
    this.internals.setFormValue(null);
    await this.listboxElement?.clearFilter();
  }

  /**
   * Focuses the input element.
   */
  @Method()
  async setFocus(): Promise<void> {
    this.inputElement?.focus();
  }

  private async openListbox(): Promise<void> {
    if (!this.listboxElement || !this.inputElement) return;

    this.isOpen = true;

    // Show the listbox as a popover
    await this.listboxElement.show();

    // Start position updates
    this.startAutoUpdate();

    // Don't auto-activate any option - let keyboard navigation handle it
    // Clear any existing active state
    this.activeDescendantId = null;
    await this.listboxElement.setActiveOption(null);
  }

  private closeListbox(): void {
    if (!this.listboxElement) return;

    this.isOpen = false;
    this.activeDescendantId = null;

    // Stop position updates
    this.stopAutoUpdate();

    // Hide the listbox popover
    this.listboxElement.hide();
  }

  private startAutoUpdate(): void {
    if (!this.inputElement || !this.listboxElement) return;

    // Use autoUpdate to handle position updates on scroll/resize
    this.clearAutoUpdate = autoUpdate(
      this.inputElement,
      this.listboxElement,
      () => this.updateListboxPosition(),
    );
  }

  private stopAutoUpdate(): void {
    if (this.clearAutoUpdate) {
      this.clearAutoUpdate();
      this.clearAutoUpdate = null;
    }
  }

  private async updateListboxPosition(): Promise<void> {
    if (!this.inputElement || !this.listboxElement) return;

    const { x, y } = await computePosition(this.inputElement, this.listboxElement, {
      placement: 'bottom-start',
      strategy: 'fixed',
      middleware: [
        offset(4),
        flip({ padding: 8 }),
        size({
          apply({ availableWidth, availableHeight, elements }) {
            Object.assign(elements.floating.style, {
              maxWidth: `${availableWidth}px`,
              maxHeight: `${Math.min(availableHeight - 16, 300)}px`,
            });
          },
        }),
      ],
    });

    Object.assign(this.listboxElement.style, {
      left: `${x}px`,
      top: `${y}px`,
      minWidth: `${this.inputElement.offsetWidth}px`,
    });
  }

  private async handleInput(e: InputEvent): Promise<void> {
    const target = e.target as HTMLInputElement;
    this.inputValue = target.value;
    this.postInput.emit({ value: this.inputValue });

    // Check if we should filter
    if (this.inputValue.length >= this.filterThreshold) {
      // Emit cancellable filter request
      const filterEvent = this.postFilterRequest.emit({ query: this.inputValue });

      // If not cancelled, perform default filtering
      if (!filterEvent.defaultPrevented && this.listboxElement) {
        await this.listboxElement.filter(this.inputValue);
      }

      // Open listbox if not already open
      if (!this.isOpen) {
        await this.openListbox();
      }
    } else {
      // Below threshold, clear filter and close
      await this.listboxElement?.clearFilter();
      if (this.isOpen && this.filterThreshold > 0) {
        this.closeListbox();
      }
    }
  }

  private handleFocus(): void {
    // Open on focus if threshold is 0
    if (this.filterThreshold === 0 && !this.isOpen) {
      this.openListbox();
    }
  }

  private handleBlur(e: FocusEvent): void {
    // Only close if focus is moving outside the autocomplete
    const relatedTarget = e.relatedTarget as Node;
    if (!this.host.contains(relatedTarget) && !this.listboxElement?.contains(relatedTarget)) {
      this.closeListbox();
    }
  }

  private async handleKeyDown(e: KeyboardEvent): Promise<void> {
    if (this.disabled) return;

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        if (!this.isOpen) {
          // Open the listbox and activate first option
          await this.openListbox();
          if (this.listboxElement) {
            this.activeDescendantId = await this.listboxElement.activateFirstOption();
          }
        } else if (this.listboxElement) {
          // Navigate to next option, or first if none active
          if (this.activeDescendantId) {
            this.activeDescendantId = await this.listboxElement.activateNextOption();
          } else {
            this.activeDescendantId = await this.listboxElement.activateFirstOption();
          }
        }
        break;

      case 'ArrowUp':
        e.preventDefault();
        if (!this.isOpen) {
          // Open the listbox and activate last option
          await this.openListbox();
          if (this.listboxElement) {
            this.activeDescendantId = await this.listboxElement.activateLastOption();
          }
        } else if (this.listboxElement) {
          // Navigate to previous option, or last if none active
          if (this.activeDescendantId) {
            this.activeDescendantId = await this.listboxElement.activatePreviousOption();
          } else {
            this.activeDescendantId = await this.listboxElement.activateLastOption();
          }
        }
        break;

      case 'Home':
        if (this.isOpen) {
          e.preventDefault();
          if (this.listboxElement) {
            this.activeDescendantId = await this.listboxElement.activateFirstOption();
          }
        }
        break;

      case 'End':
        if (this.isOpen) {
          e.preventDefault();
          if (this.listboxElement) {
            this.activeDescendantId = await this.listboxElement.activateLastOption();
          }
        }
        break;

      case 'Enter':
        if (this.isOpen && this.activeDescendantId) {
          e.preventDefault();
          await this.listboxElement?.selectActiveOption();
        }
        break;

      case 'Escape':
        if (this.isOpen) {
          e.preventDefault();
          this.closeListbox();
          this.inputElement?.focus();
        }
        break;

      case 'Tab':
        // Accept selection if there's an active option
        if (this.isOpen && this.activeDescendantId) {
          await this.listboxElement?.selectActiveOption();
        }
        this.closeListbox();
        break;

      case ' ':
        // Space opens the listbox if closed and input is empty
        if (!this.isOpen && this.inputValue === '') {
          e.preventDefault();
          await this.openListbox();
        }
        break;
    }
  }

  private handleClearClick(e: MouseEvent): void {
    e.preventDefault();
    e.stopPropagation();
    this.clear();
    this.inputElement?.focus();
  }

  private announceResults(count: number): void {
    if (!this.liveRegionElement) return;

    const message =
      count === 0
        ? this.noResultsText
        : count === 1
          ? '1 result available'
          : `${count} results available`;

    this.liveRegionElement.textContent = message;
  }

  private boundHandleInput = this.handleInput.bind(this);
  private boundHandleFocus = this.handleFocus.bind(this);
  private boundHandleBlur = this.handleBlur.bind(this);
  private boundHandleKeyDown = this.handleKeyDown.bind(this);

  componentWillLoad() {
    // Find the listbox element in light DOM
    this.listboxElement = this.host.querySelector('post-listbox') as PostListboxElement | null;
  }

  componentDidLoad() {
    this.validateFilterThreshold();
    this.setupInputElement();

    // Initialize form value
    if (this.value) {
      this.internals.setFormValue(this.value);
    }

    // Set up listbox attributes
    if (this.listboxElement) {
      this.listboxElement.setAttribute('data-empty-message', this.noResultsText);
    }
  }

  private setupInputElement(): void {
    // Find the input element in the light DOM
    this.inputElement = this.host.querySelector('input');

    if (this.inputElement) {
      // Set up ARIA attributes on the input
      this.inputElement.setAttribute('role', 'combobox');
      this.inputElement.setAttribute('aria-autocomplete', 'list');
      this.inputElement.setAttribute('aria-expanded', 'false');
      this.inputElement.setAttribute('aria-haspopup', 'listbox');

      if (this.listboxElement) {
        this.inputElement.setAttribute('aria-controls', this.listboxElement.id);
      }

      // Attach event listeners using bound functions for proper cleanup
      this.inputElement.addEventListener('input', this.boundHandleInput);
      this.inputElement.addEventListener('focus', this.boundHandleFocus);
      this.inputElement.addEventListener('blur', this.boundHandleBlur);
      this.inputElement.addEventListener('keydown', this.boundHandleKeyDown);
    }
  }

  private updateInputAriaExpanded(): void {
    if (this.inputElement) {
      this.inputElement.setAttribute('aria-expanded', this.isOpen ? 'true' : 'false');
      if (this.activeDescendantId) {
        this.inputElement.setAttribute('aria-activedescendant', this.activeDescendantId);
      } else {
        this.inputElement.removeAttribute('aria-activedescendant');
      }
    }
  }

  componentDidUpdate() {
    this.updateInputAriaExpanded();
  }

  disconnectedCallback() {
    // Stop auto updates
    this.stopAutoUpdate();

    // Clean up event listeners using the same bound functions
    if (this.inputElement) {
      this.inputElement.removeEventListener('input', this.boundHandleInput);
      this.inputElement.removeEventListener('focus', this.boundHandleFocus);
      this.inputElement.removeEventListener('blur', this.boundHandleBlur);
      this.inputElement.removeEventListener('keydown', this.boundHandleKeyDown);
    }
  }

  render() {
    return (
      <Host
        data-version={version}
        class={{
          'is-open': this.isOpen,
          'is-disabled': this.disabled,
        }}
      >
        <div class="autocomplete-wrapper">
          <div class="autocomplete-input-container">
            <slot></slot>
            {this.clearable && this.inputValue && (
              <button
                type="button"
                class="autocomplete-clear-button"
                aria-label="Clear selection"
                onClick={this.handleClearClick.bind(this)}
                tabindex="-1"
              >
                <post-icon name="2063"></post-icon>
              </button>
            )}
          </div>

          {/* Live region for screen reader announcements */}
          <div
            ref={el => (this.liveRegionElement = el)}
            class="visually-hidden"
            aria-live="polite"
            aria-atomic="true"
          ></div>
        </div>
      </Host>
    );
  }

  formAssociatedCallback() {
    if (this.value) {
      this.internals.setFormValue(this.value);
    }
  }

  formDisabledCallback(disabled: boolean) {
    this.disabled = disabled;
    if (this.inputElement) {
      this.inputElement.disabled = disabled;
    }
  }

  formResetCallback() {
    this.clear();
  }
}
