import '@swisspost/design-system-styles/cargo-default.css';
import '@swisspost/design-system-components-react/post-components.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { readonly children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main style={{ paddingBlock: '3rem' }}>
          <div className="container">{children}</div>
        </main>
      </body>
    </html>
  );
}
