version: 2
snapshot:
  widths:
    - 320
    - 1440
  minHeight: 680
  percyCSS: ""
  enable-javascript: true
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
