###
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
# NOTE: pnpm caching support requires pnpm version >= 6.10.0
#
###

name: Setup pnpm
description: Provides node and pnpm in a specific version.

inputs:
  use_cache:
    description: Specify whether to use the pnpm cache or not
    default: true
    type: boolean

runs:
  using: composite
  steps:
    - name: Install pnpm and runtime
      uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
      with:
        runtime: node
        install: false
        cache: ${{ inputs.use_cache }}

    - name: Summary
      shell: bash
      run: |
        echo "Installed versions:"
        echo "- node: $(node -v)"
        echo "- npm: $(npm -v)"
        echo "- pnpm: $(pnpm -v)"
