###
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
# NOTE: pnpm caching support requires pnpm version >= 6.10.0
#
###

name: Setup pnpm
description: Provides node and pnpm in a specific version.

inputs:
  node_version:
    description: Specify the node version to install
    type: string
  pnpm_version:
    description: Specify the pnpm version to install
    type: string
  use_cache:
    description: Specify wether to use the pnpm cache or not
    default: true
    type: boolean

runs:
  using: composite
  steps:
    - name: Detect wanted version
      id: wanted-versions
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b
      with:
        script: |
          const fs = require('fs')
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))

          return {
            node: pkg.engines?.node,
            pnpm: pkg.packageManager
          }

    - name: Install pnpm
      uses: pnpm/action-setup@d648c2dd069001a242c621c8306af467f150e99d
      with:
        # If input.pnpm_version is NOT defined,
        # the action automatically uses the "packageManager" field from the package.json file
        # If input.pnpm_version is defined, we need to point to another package.json file, without the "packageManager" field,
        # so we do not end up with a "Multiple versions of pnpm specified" error
        package_json_file: ${{ inputs.pnpm_version && 'packages/documentation/package.json' || 'package.json' }}
        version: ${{ inputs.pnpm_version || null }}

    - name: Install node
      uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
      with:
        node-version: ${{ inputs.node_version || fromJSON(steps.wanted-versions.outputs.result).node }}
        cache: ${{ inputs.use_cache == 'true' && 'pnpm' || '' }}

    - name: Summary
      shell: bash
      run: |
        echo "Installed versions:"
        echo "- node: $(node -v)"
        echo "- npm: $(npm -v)"
        echo "- pnpm: $(pnpm -v)"
