###
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# If you need to do some changes in a local-action used in this
# workflow, make sure you change the action-flag to your working
# branch-name to get the latest action functionality.
#
# Example: swisspost/design-system/.github/actions/setup-pnpm@my-working-branch-name
#
# Don't forget to change the action-flag back to 'main',
# once you have finished your work on the local-action!
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
# NOTE: pnpm caching support requires pnpm version >= 6.10.0
#
###

name: Setup pnpm
description: Provides node and pnpm in a specific version.

inputs:
  node_version:
    description: Specify the node version to install
    default: 18
    type: string
  pnpm_version:
    description: Specify the pnpm version to install
    default: 8
    type: string
  use_cache:
    description: Specify wether to use the pnpm cache or not
    default: true
    type: boolean

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm_version }}

    - name: Install node with pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.use_cache == 'true' && 'pnpm' || '' }}
