###
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
# NOTE: pnpm caching support requires pnpm version >= 6.10.0
#
###

name: Setup pnpm
description: Provides node and pnpm in a specific version.

inputs:
  node_version:
    description: Specify the node version to install
    type: string
  pnpm_version:
    description: Specify the pnpm version to install
    type: string
  use_cache:
    description: Specify wether to use the pnpm cache or not
    default: true
    type: boolean

runs:
  using: composite
  steps:
    - name: Detect wanted version
      id: wanted-versions
      uses: actions/github-script@e7aeb8c663f696059ebb5f9ab1425ed2ef511bdb
      with:
        script: |
          const fs = require('fs')
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))

          return {
            node: pkg.engines?.node,
            pnpm: pkg.packageManager
          }

    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      with:
        # If input.pnpm_version is NOT defined,
        # the action automatically uses the "packageManager" field from the package.json file
        # If input.pnpm_version is defined, we need to point to another package.json file, without the "packageManager" field,
        # so we do not end up with a "Multiple versions of pnpm specified" error
        package_json_file: ${{ inputs.pnpm_version && 'packages/documentation/package.json' || 'package.json' }}
        version: ${{ inputs.pnpm_version || null }}

    - name: Install node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: ${{ inputs.node_version || fromJSON(steps.wanted-versions.outputs.result).node }}
        cache: ${{ inputs.use_cache == 'true' && 'pnpm' || '' }}

    - name: Summary
      shell: bash
      run: |
        echo "Installed versions:"
        echo "- node: $(node -v)"
        echo "- pnpm: $(pnpm -v)"
