import { resolve } from 'path';

export const SOURCE_PATH = resolve('./tokensstudio-generated/');
export const OUTPUT_PATH = resolve('./dist/');

export const FILE_HEADER = [
  'Do not edit manually',
  'This file was generated by the swisspost/design-system-tokens package',
  new Date().toUTCString(),
];

/**
 * Enum for possible tokenset names.
 * @readonly
 * @enum {string}
 */
export const TOKENSET_NAMES = {
  Core: 'core',
  Scheme: 'scheme',
  Device: 'device',
  Channel: 'channel',
  Theme: 'theme',
  Elements: 'elements',
  Components: 'components',
  Utilities: 'utilities',
  Palettes: 'palettes',
  Helpers: 'helpers',
};

export const EXPLICIT_COMPONENT_LAYER_GROUPNAMES = [
  'elements',
  'components',
  'utilities',
  'helpers',
];
export const EXPLICIT_FIGMAONLY_GROUPNAMES = ['figmaonly'];
export const EXPLICIT_FIGMAONLY_SETNAMES = ['figmaonly'];
export const TOKENSET_LAYERS = {
  core: 'core',
  semantic: 'semantic',
  component: 'component',
};
export const TOKENSET_PREFIX = 'post';
export const CUSTOM_FORMAT_INDENT = '  ';

// https://docs.tokens.studio/token-types/token-type-overview#available-token-types
export const NO_UNITLESS_ZERO_VALUE_TOKEN_TYPES = [
  'fontSize',
  'lineHeight',
  'letterSpacing',
  'paragraphSpacing',
  'dimension',
  'borderRadius',
  'borderWidth',
  'spacing',
  'sizing',
];
