###
#
# If you need to do some changes in a local-action used in this
# workflow, make sure you change the action-flag to your working
# branch-name to get the latest action functionality.
#
# Example: swisspost/design-system/.github/actions/setup-environment-pnpm@my-working-branch-name
#
# Don't forget to change the action-flag back to 'main',
# once you have finished your work on the local-action!
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
###

name: Artefact Upload Folder
description: Uploads an entire artefact folder to share data between jobs and store data once a workflow is complete.

inputs:
  name:
    description: Name of the artefact
    required: true
    type: string
  path:
    description: Path to the artefact folder
    required: true
    type: string

runs:
  using: composite
  steps:
    # - uses: actions/upload-artefact@v3
    #   with:
    #     name: ${{ inputs.name }}
    #     path: ${{ inputs.path }}
