import { Component } from '@angular/core';
import {
  PostAccordion,
  PostAccordionItem,
  PostAutocomplete,
  PostAvatar,
  PostBanner,
  PostClosebutton,
  PostCollapsible,
  PostCollapsibleTrigger,
  PostDatePicker,
  PostIcon,
  PostLinkarea,
  PostListbox,
  PostListboxOption,
  PostMenu,
  PostMenuItem,
  PostMenuTrigger,
  PostNumberInput,
  PostPagination,
  PostPopover,
  PostPopoverTrigger,
  PostRating,
  PostStepper,
  PostStepperItem,
  PostTabItem,
  PostTabPanel,
  PostTabs,
  PostTogglebutton,
} from 'components';

@Component({
  selector: 'home-page',
  templateUrl: './home.component.html',
  standalone: true,
  imports: [
    PostAccordion,
    PostAccordionItem,
    PostAutocomplete,
    PostAvatar,
    PostBanner,
    PostClosebutton,
    PostCollapsible,
    PostCollapsibleTrigger,
    PostDatePicker,
    PostIcon,
    PostLinkarea,
    PostListbox,
    PostListboxOption,
    PostMenu,
    PostMenuItem,
    PostMenuTrigger,
    PostNumberInput,
    PostPagination,
    PostPopover,
    PostPopoverTrigger,
    PostRating,
    PostStepper,
    PostStepperItem,
    PostTabItem,
    PostTabPanel,
    PostTabs,
    PostTogglebutton,
  ],
})
export class HomeComponent {}
