import { Component } from '@angular/core';
import {
  PostAccordion,
  PostAccordionItem,
  PostAvatar,
  PostBanner,
  PostCardControl,
  PostCollapsible,
  PostCollapsibleTrigger,
  PostIcon,
  PostLinkarea,
  PostMenu,
  PostMenuTrigger,
  PostMenuItem,
  PostPagination,
  PostPopover,
  PostPopovercontainer,
  PostPopoverTrigger,
  PostRating,
  PostTabHeader,
  PostTabPanel,
  PostTabs,
  PostTooltip,
  PostTooltipTrigger,
  PostStepper,
  PostStepperItem,
} from 'components';

@Component({
  selector: 'home-page',
  templateUrl: './home.component.html',
  standalone: true,
  imports: [
    PostAccordion,
    PostAccordionItem,
    PostAvatar,
    PostBanner,
    PostCardControl,
    PostCollapsible,
    PostCollapsibleTrigger,
    PostIcon,
    PostLinkarea,
    PostMenu,
    PostMenuTrigger,
    PostMenuItem,
    PostPagination,
    PostPopover,
    PostPopovercontainer,
    PostPopoverTrigger,
    PostRating,
    PostTabHeader,
    PostTabPanel,
    PostTabs,
    PostTooltip,
    PostTooltipTrigger,
    PostStepper,
    PostStepperItem,
  ],
})
export class HomeComponent {
  isCollapsed = false;
}
