###
#
# Build the packages/documentation storybook
#
# This workflow does not have secrets when run from a fork.
# Artifacts are uploaded and used in a subsequent workflow
# with more privileges which does not run unsafe commands.
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Build Documentation V7
on:
  pull_request:
    paths:
      - 'packages/documentation-v7/**'
      - 'packages/styles/**'
      - 'packages/components/**'
      - 'packages/internet-header/**'
      - 'packages/icons/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      - name: Install documentation-v7 & dependencies
        run: pnpm --filter design-system-documentation-v7... install

      - name: Build documentation-v7 & dependencies
        run: pnpm --filter design-system-documentation-v7... build

      - name: Upload documentation-v7
        uses: swisspost/design-system/.github/actions/artifact-upload@main
        with:
          name: design-system-documentation-v7
          folder: packages/documentation-v7/storybook-static
