###
#
# Deploy a pre-built packages/components storybook to netilfy
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Deploy Components Storybook to Netlify
on:
  workflow_run:
    workflows: ['Build Components Storybook']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      - name: Download build artifacts
        uses: swisspost/design-system/.github/actions/artifact-download@main
        id: build
        with:
          name: design-system-components-storybook
          folder: build-output

      - name: Deploy to Netlify
        uses: swisspost/design-system/.github/actions/deploy-to-netlify@main
        id: deploy
        with:
          id: ${{ steps.build.outputs.id }}
          action: ${{ steps.build.outputs.action }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.COMPONENTS_NETLIFY_SITE_ID }}
          netlify_site_url: swisspost-design-system-components.netlify.app
          folder: ${{ steps.build.outputs.folder }}
