name: Deploy Documentation Preview
on:
  workflow_run:
    workflows: ['Build Documentation']
    types: [completed]

jobs:
  deploy:
    name: Deploy Documentation Preview
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup pnpm & node
        uses: ./.github/actions/setup-pnpm

      - name: Setup netlify-cli
        uses: ./.github/actions/setup-netlify-cli

      - name: Create temporary directory for artifacts
        run: mkdir -p ${{ runner.temp }}/artifacts/

      - name: Download build artifacts
        uses: ./.github/actions/artifact-download
        id: build
        with:
          name: design-system-documentation
          folder: ${{ runner.temp }}/artifacts/

      - name: Get netlify config
        id: netlify-config
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const fs = require('fs');
            return JSON.parse(fs.readFileSync('${{ steps.build.outputs.folder }}/netlify.config.json', 'utf8'));

      - name: Remove netlify.config.json from artifact folder
        run: rm ${{ steps.build.outputs.folder }}/netlify.config.json

      - name: Generate Safe URL Alias
        id: generate-url
        env:
          BUILD_ID: ${{ steps.build.outputs.id }}
        run: |
          safe_id=$(echo "$BUILD_ID" | iconv -t ascii//TRANSLIT | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)
          url_alias="preview-${safe_id}"
          echo "url-alias=$url_alias" >> $GITHUB_OUTPUT

      - name: Deploy Documentation Preview
        id: deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ fromJSON(steps.netlify-config.outputs.result).siteId }}
          SITE_URL: ${{ fromJSON(steps.netlify-config.outputs.result).siteUrl }}
          FOLDER: ${{ steps.build.outputs.folder }}
          URL_ALIAS: ${{ steps.generate-url.outputs.url-alias }}
        run: |
          echo "site-url=https://$URL_ALIAS--$SITE_URL" >> $GITHUB_OUTPUT
          netlify deploy \
            --filter @swisspost/design-system-documentation \
            --dir "$FOLDER" \
            --alias "$URL_ALIAS"

      - name: Create preview message
        uses: ./.github/actions/preview/message/create
        with:
          access-token: ${{ secrets.SWISSPOSTDEVS_ACCESS_TOKEN }}
          issue-number: ${{ steps.build.outputs.id }}

      - name: Update preview message
        uses: ./.github/actions/preview/message/update
        with:
          access-token: ${{ secrets.SWISSPOSTDEVS_ACCESS_TOKEN }}
          issue-number: ${{ steps.build.outputs.id }}
          preview-url: ${{ steps.deploy.outputs.site-url }}

      - name: Create Summary
        id: summary
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            return `# Deployed Documentation Preview\n- SiteId: <code>${{ fromJSON(steps.netlify-config.outputs.result).siteId }}</code>\n- SiteUrl: ${{ steps.deploy.outputs.site-url }}`;

      - name: Output Summary
        run: echo -e "${{ steps.summary.outputs.result }}" >> $GITHUB_STEP_SUMMARY
