###
#
# Deploys a pre-built documentation to chromatic
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Deploy Documentation to Chromatic

on:
  pull_request:
    paths:
      - 'packages/documentation/**'

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      - name: Install documentation & dependencies
        run: pnpm --filter design-system-documentation... install

      # documentation package will be built by chromatic itself
      - name: Build documentation & dependencies
        run: pnpm --filter design-system-documentation^... build

      - name: Publish documentation to chromatic
        uses: chromaui/action@v1
        # Options required to the GitHub Chromatic Action
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_STORYBOOK_TOKEN }}
          workingDir: packages/documentation
