###
#
# Deploy a pre-built documentation to netilfy
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Deploy Documentation V7 Preview to Netlify
on:
  workflow_run:
    workflows: ['Build Documentation V7']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      - name: Download build artifacts
        uses: swisspost/design-system/.github/actions/artifact-download@main
        id: build
        with:
          name: design-system-documentation-v7
          folder: build-output

      - name: Deploy documentation v7 to netlify
        uses: swisspost/design-system/.github/actions/deploy-to-netlify@main
        id: deploy
        with:
          id: ${{ steps.build.outputs.id }}
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.NEXTV7_NETLIFY_SITE_ID }}
          netlify_site_url: swisspost-design-system-next-v7.netlify.app
          folder: ${{ steps.build.outputs.folder }}
          comment_token: ${{ secrets.SWISSPOSTDEVS_ACCESS_TOKEN }}
          comment_author: swisspost-bot
