name: Dry Run Publish

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    paths:
      - ".changeset/**"

jobs:
  dry-run-publish:
    name: Dry Run Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Dry Run Publish
        run: pnpm -r publish --dry-run

      - name: Output Summary
        id: summary
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            return `## Dry Run Publish Results
            This workflow ran a dry-run of the publish process to detect potential release issues. 
            - **Branch:** \`${{ github.ref_name }}\`
            - **Trigger:** Pull Request modifying \`main\`
            - **Status:** Completed
            `
      - name: Post Summary
        run: echo -e ${{ steps.summary.outputs.result }} >> $GITHUB_STEP_SUMMARY
