name: End to end tests - Angular
on:
  pull_request:
    paths:
      - 'packages/components-angular/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-pnpm

      - name: Install & build dependencies
        run: pnpm install && pnpm --filter design-system-components-angular-workspace^... build

      - name: Build consumer app
        run: pnpm --filter design-system-components-angular-workspace exec ng build consumer-app

      - name: Install Playwright browsers
        run: pnpm --filter design-system-components-angular-workspace exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm --filter design-system-components-angular-workspace e2e:ci

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results-angular
          path: packages/components-angular/projects/consumer-app/playwright/results
          retention-days: 14