name: Print package.json version
on: [pull_request]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Check version
      - name: Version Check
        uses: swisspost/design-system/.github/actions/compare-package-version@main
        id: check
        with:
          path: ./packages/styles/package.json

      - name: Print version
        run: 'echo hasChanged: ${{steps.check.outputs.versionChanged}}, currentPackageVersion: ${{steps.check.outputs.currentVersion}}, lastVersion: ${{steps.check.outputs.lastVersion}}'
