name: Test workflow
on: push

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if version has changed
        id: check # This will be the reference for getting the outputs.
        uses: EndBug/version-check@v2 # You can choose the version/branch you prefer.
        with:
          file-name: ./packages/demo/package.json
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from branch name
        id: branch
        run: |
          ref=${{github.ref}}
          echo "branch_version=swisspost-design-system-${ref##*/}" >> "$GITHUB_OUTPUT"

  fail:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  test2:
    runs-on: ubuntu-latest
    if: always() && needs.success.outputs.changed == false
    needs: [success, fail]
    steps:
      - name: Always step
        run: echo "Always! ${{needs.success.outputs.branch_version}}"
