###
#
# Runs all tests in packages changed since main
#
###

name: Component cypress tests
on: 
  pull_request:
    paths:
      - packages/components/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.13.0

      - name: Install deps
        run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          install: false
          build: pnpm --filter design-system-components stencil:build
          start: pnpm --filter design-system-components storybook:start:headless
          command-prefix: pnpm --filter design-system-components exec
          wait-on: 'http://localhost:9303'
