###
#
# Runs all tests in packages changed since main
#
###

name: Run tests
on: 
  pull_request:
    paths:
      - packages/components/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          install: pnpm --filter design-system-components install
          build: pnpm --filter design-system-components stencil:build
          start: pnpm --filter design-system-components storybook:start:headless
          test: pnpm --filter design-system-components cypress:run
          wait-on: 'http://localhost:9303'
          project: ./packages/components
