name: Test workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read branch name
        id: branch
        run: |
          ref=${{github.ref}}
          echo "branch_version=${ref##*/}" >> "$GITHUB_OUTPUT"

      - name: Print result
        run: echo "${{steps.branch.outputs.branch_version}}"

      - name: Create netlify site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify sites:list
