name: Test workflow
on: push

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - name: good
        run: exit 0
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  test2:
    runs-on: ubuntu-latest
    if: always() && needs.success.result == 'success'
    needs: [success, fail]
    steps:
      - name: Always step
        run: echo "Always!"
