name: Test workflow
on: push

jobs:
  success:
    runs-on: ubuntu-latest
    outputs:
      branch_version: ${{steps.branch.outputs.branch_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if version has changed
        id: check # This will be the reference for getting the outputs.
        uses: EndBug/version-check@v2 # You can choose the version/branch you prefer.
        with:
          file-name: ./packages/demo/package.json
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from branch name
        id: branch
        run: |
          ref=${{github.ref}}
          branch_version="${ref##*/}"
          site_id=swisspost-design-system-${branch_version}
          echo "site_id=$site_id" >> "$GITHUB_OUTPUT"
          echo "branch_version=$branch_version" >> "$GITHUB_OUTPUT"

      - name: Echo
        run: echo "${{steps.branch.outputs.branch_version}} and ${{steps.branch.outputs.site_id}}"

      - name: Add redirect rule
        run: |
          redirect_path="./_test"
          echo "/${{steps.branch.outputs.branch_version}} https://${{steps.branch.outputs.site_id}}.netlify.app 200" >> "$redirect_path"

      - name: Commit file
        run: |
          git add "./_test"
          git commit -m "chore(release/${{steps.branch.outputs.branch_version}}): ↪️ update redirects"
          git push -u origin "add-redirects-for-${{steps.branch.outputs.branch_version}}"

      - name: Open PR
        run: |

  fail:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  test2:
    runs-on: ubuntu-latest
    if: always() && needs.success.outputs.changed == false
    needs: [success, fail]
    steps:
      - name: Always step
        run: echo "Always! ${{needs.success.outputs.branch_version}}"
