###
#
# runs all tests in packages changed since main
#
###

name: Turborepo remote caching
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-pnpm

      - name: Install dependencies of changed packages
        run: pnpm install

      - name: Turbo build
        run: pnpm turbo run build
